# @module seed_tvi — Modelos TVI Ramo 1: GERAL (TVI-01 a TVI-08)
"""
Modelos profissionais do Ramo GERAL com novo schema unificado.
Cada campo possui id EXCLUSIVO — nenhum campo e compartilhado entre modelos.
Schema: {id, nome, ramo, aplicacao, normas, requer_art, campos_especificos, secoes_obrigatorias}
"""

MODELOS_GERAL = [
    # TVI-01 — Avaliacao PTAM
    {
        "id": "TVI-01",
        "nome": "Avaliacao PTAM — Parecer Tecnico de Avaliacao Mercadologica",
        "ramo": "GERAL",
        "aplicacao": "Vistoria vinculada ao PTAM para determinacao de valor de mercado de imovel urbano, "
                     "com enquadramento normativo NBR 14653-2 e indicacao de grau de fundamentacao.",
        "normas": [
            "NBR 14653-1:2019 — Avaliacao de bens: Procedimentos gerais",
            "NBR 14653-2:2011 — Avaliacao de imoveis urbanos",
            "COFECI Resolucao 957/2006 — PTAM",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "ptam01_metodo_avaliacao",
                "secao": "Metodologia Avaliatoria",
                "tipo": "select",
                "label": "Metodo de Avaliacao Adotado",
                "opcoes": [
                    "Metodo Comparativo de Dados de Mercado",
                    "Metodo da Renda",
                    "Metodo Evolutivo (Custo)",
                    "Metodo Involutivo",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Selecione o metodo principal conforme NBR 14653-2.",
            },
            {
                "id": "ptam01_valor_unitario_m2",
                "secao": "Resultado da Avaliacao",
                "tipo": "number",
                "label": "Valor Unitario de Avaliacao (R$/m2)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 5200.00",
                "ajuda": "Valor unitario homogeneizado apos aplicacao dos fatores.",
            },
            {
                "id": "ptam01_fator_homogeneizacao",
                "secao": "Metodologia Avaliatoria",
                "tipo": "number",
                "label": "Fator de Homogeneizacao Global (FH)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 1.05",
                "ajuda": "Produto de todos os fatores parciais aplicados a amostra.",
            },
            {
                "id": "ptam01_pesquisa_mercado",
                "secao": "Pesquisa de Mercado",
                "tipo": "tabela",
                "label": "Elementos da Amostra de Mercado",
                "opcoes": ["Endereco", "Area m2", "Valor R$", "Valor R$/m2", "Fonte", "Data pesquisa", "Fatores"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Registre cada elemento da amostra com localizacao, area, valor e fonte.",
            },
            {
                "id": "ptam01_valor_avaliacao_final",
                "secao": "Resultado da Avaliacao",
                "tipo": "number",
                "label": "Valor de Avaliacao Final (R$)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 520000.00",
                "ajuda": "Valor total resultante apos homogeneizacao e arredondamento tecnico.",
            },
            {
                "id": "ptam01_enquadramento_sfh_sfi",
                "secao": "Resultado da Avaliacao",
                "tipo": "select",
                "label": "Enquadramento SFH / SFI",
                "opcoes": ["SFH — dentro do teto", "SFI — acima do teto SFH", "Nao aplicavel"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Indica se o valor se enquadra nos limites do SFH vigente.",
            },
            {
                "id": "ptam01_depreciacao_ross_heidecke",
                "secao": "Avaliacao do Imovel",
                "tipo": "number",
                "label": "Depreciacao Ross-Heidecke (%)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 18.5",
                "ajuda": "Percentual de depreciacao calculado pelo metodo Ross-Heidecke conforme NBR 14653-2.",
            },
            {
                "id": "ptam01_cub_regional",
                "secao": "Avaliacao do Imovel",
                "tipo": "number",
                "label": "CUB/m2 Regional Referencia (R$/m2)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 2450.00",
                "ajuda": "CUB do mes da avaliacao para o padrao construtivo equivalente, divulgado pelo SINDUSCON regional.",
            },
            {
                "id": "ptam01_grau_fundamentacao",
                "secao": "Resultado da Avaliacao",
                "tipo": "select",
                "label": "Grau de Fundamentacao (NBR 14653-2)",
                "opcoes": ["Grau I — Minimo", "Grau II — Normal", "Grau III — Maximo"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Grau de fundamentacao conforme pontuacao dos quesitos exigidos pela norma.",
            },
            {
                "id": "ptam01_numero_art",
                "secao": "Responsabilidade Tecnica",
                "tipo": "text",
                "label": "Numero ART (CREA) / TRT (CAU)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: ART 2024-123456-7",
                "ajuda": "ART obrigatoria para PTAM conforme Resolucao CONFEA 1.094/2017.",
            },
        ],
        "secoes_obrigatorias": [
            "Metodologia Avaliatoria",
            "Avaliacao do Imovel",
            "Pesquisa de Mercado",
            "Resultado da Avaliacao",
            "Responsabilidade Tecnica",
        ],
    },

    # TVI-02 — Compra e Venda
    {
        "id": "TVI-02",
        "nome": "Vistoria de Compra e Venda",
        "ramo": "GERAL",
        "aplicacao": "Registro tecnico do estado fisico e documental do imovel no contexto de transacao "
                     "de compra e venda, subsidiando decisao de aquisicao e instrumento contratual.",
        "normas": [
            "NBR 14653-1:2019 — Procedimentos gerais",
            "Lei 6.530/1978 — Atividade do corretor",
            "CC/2002 Art. 441 a 444 — Vicios redibiotorios",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "cv02_valor_transacao",
                "secao": "Dados da Transacao",
                "tipo": "number",
                "label": "Valor da Transacao (R$)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 450000.00",
                "ajuda": "Valor acordado entre as partes para a transacao de compra e venda.",
            },
            {
                "id": "cv02_situacao_matricula",
                "secao": "Situacao Documental",
                "tipo": "select",
                "label": "Situacao da Matricula",
                "opcoes": [
                    "Regular — sem onus ou gravames",
                    "Com hipoteca",
                    "Com penhora judicial",
                    "Com alienacao fiduciaria",
                    "Bloqueada / Indisponivel",
                    "Matricula nao localizada",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao verificada na certidao de matricula atualizada (< 30 dias).",
            },
            {
                "id": "cv02_onus_gravames",
                "secao": "Situacao Documental",
                "tipo": "caixa_texto",
                "label": "Descricao de Onus e Gravames",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva os onus identificados na matricula...",
                "ajuda": "Detalhe hipotecas, penhoras, usufruto, servidoes e demais restricoes.",
            },
            {
                "id": "cv02_divergencia_area",
                "secao": "Situacao Documental",
                "tipo": "number",
                "label": "Divergencia Area Real vs. Registrada (m2)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 5.00 (positivo = real maior; negativo = real menor)",
                "ajuda": "Diferenca entre a area medida in loco e a area constante na matricula.",
            },
            {
                "id": "cv02_condicoes_suspensivas",
                "secao": "Dados da Transacao",
                "tipo": "caixa_texto",
                "label": "Condicoes Suspensivas / Precedentes",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: aprovacao do financiamento, regularizacao do ITBI...",
                "ajuda": "Liste todas as condicoes que devem ser cumpridas antes da conclusao da venda.",
            },
            {
                "id": "cv02_checklist_documentacao",
                "secao": "Situacao Documental",
                "tipo": "multiselect",
                "label": "Checklist de Documentacao",
                "opcoes": [
                    "Matricula atualizada (< 30 dias)",
                    "Certidao negativa de onus e acoes reipersecutorias",
                    "IPTU do exercicio em dia",
                    "Habite-se / Auto de conclusao",
                    "Planta aprovada pela prefeitura",
                    "ART ou TRT do projeto",
                    "AVCB vigente (se aplicavel)",
                    "Declaracao de quitacao condominial",
                    "Certidao negativa de debitos do vendedor (CPF/CNPJ)",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque todos os documentos que foram verificados.",
            },
            {
                "id": "cv02_estado_conservacao_nota",
                "secao": "Estado Fisico",
                "tipo": "number",
                "label": "Estado de Conservacao — Nota (1 a 10)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "1 = pessimo ... 10 = novo",
                "ajuda": "Nota global do estado de conservacao atribuida pelo vistoriador.",
            },
            {
                "id": "cv02_itens_incluidos_venda",
                "secao": "Dados da Transacao",
                "tipo": "caixa_texto",
                "label": "Itens Incluidos na Venda",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: ar-condicionado, persianas, fogao embutido...",
                "ajuda": "Liste todos os bens moveis e equipamentos incluidos no negocio.",
            },
            {
                "id": "cv02_pendencias_regularizacao",
                "secao": "Pendencias",
                "tipo": "caixa_texto",
                "label": "Pendencias de Regularizacao",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: averbaçao de construcao, regularizacao de area acrescida...",
                "ajuda": "Descreva as pendencias que precisam ser resolvidas antes ou apos a venda.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados da Transacao",
            "Situacao Documental",
            "Estado Fisico",
            "Pendencias",
        ],
    },

    # TVI-03 — Entrega de Imovel Novo
    {
        "id": "TVI-03",
        "nome": "Vistoria de Entrega de Imovel Novo",
        "ramo": "GERAL",
        "aplicacao": "Vistoria de entrega de unidade nova pela construtora/incorporadora ao comprador, "
                     "verificando conformidade com memorial descritivo, projeto e NBR 15575.",
        "normas": [
            "NBR 15575:2013 — Desempenho de edificacoes habitacionais",
            "NBR 16280:2015 — Sistema de manutencao",
            "Lei 4.591/1964 — Incorporacoes imobiliarias",
            "CDC Art. 18 — Defeitos em produtos",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "ent03_conformidade_memorial",
                "secao": "Conformidade Tecnica",
                "tipo": "select",
                "label": "Conformidade com Memorial Descritivo",
                "opcoes": [
                    "Totalmente conforme",
                    "Conforme com divergencias menores",
                    "Divergencias significativas — construtora notificada",
                    "Nao conforme — recusa justificada",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Compare item a item do memorial descritivo contratual com o entregue.",
            },
            {
                "id": "ent03_checklist_comodo",
                "secao": "Vistoria por Comodo",
                "tipo": "tabela",
                "label": "Checklist por Comodo",
                "opcoes": ["Comodo", "Piso", "Parede", "Forro", "Esquadrias", "Eletrica", "Hidraulica", "Observacao"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Registre cada comodo com avaliacao de todos os sistemas e acabamentos.",
            },
            {
                "id": "ent03_pontos_eletricos_por_ambiente",
                "secao": "Instalacoes Eletricas",
                "tipo": "tabela",
                "label": "Pontos Eletricos por Ambiente",
                "opcoes": ["Ambiente", "Tomadas previstas", "Tomadas instaladas", "Interruptores", "Luminárias", "Conforme"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Confira a quantidade de pontos eletricos conforme projeto aprovado.",
            },
            {
                "id": "ent03_pisos_revestimentos_entregues",
                "secao": "Acabamentos",
                "tipo": "caixa_texto",
                "label": "Pisos e Revestimentos Entregues",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: sala — porcelanato 60x60cm; banheiro — ceramica 45x45cm...",
                "ajuda": "Descreva os materiais entregues conforme memorial descritivo.",
            },
            {
                "id": "ent03_equipamentos_entregues",
                "secao": "Equipamentos",
                "tipo": "tabela",
                "label": "Equipamentos Entregues",
                "opcoes": ["Equipamento", "Marca/Modelo", "Localizacao", "Funcionando", "Numero serie"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste todos os equipamentos incluidos na entrega (ar-cond., aquecedor, etc.).",
            },
            {
                "id": "ent03_vicios_aparentes",
                "secao": "Nao Conformidades",
                "tipo": "multiselect",
                "label": "Vicios Aparentes Identificados",
                "opcoes": [
                    "Fissuras em revestimento",
                    "Infiltracao visivel",
                    "Piso desnivelado ou solto",
                    "Esquadria com folga ou travamento",
                    "Pintura com falhas ou bolhas",
                    "Louca ou metal danificado",
                    "Instalacao eletrica irregular",
                    "Instalacao hidraulica com vazamento",
                    "Sem vicios aparentes",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque todos os vicios aparentes verificados no momento da entrega.",
            },
            {
                "id": "ent03_prazo_garantia_nbr15575",
                "secao": "Garantias",
                "tipo": "caixa_texto",
                "label": "Prazos de Garantia (conforme NBR 15575)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: fundacoes — 10 anos; impermeabilizacao — 5 anos; pintura — 2 anos...",
                "ajuda": "Registre os prazos de garantia minimos conforme tabela da NBR 15575:2013.",
            },
            {
                "id": "ent03_aceite_recusa",
                "secao": "Conclusao da Entrega",
                "tipo": "select",
                "label": "Aceite ou Recusa da Entrega",
                "opcoes": [
                    "Aceito sem ressalvas",
                    "Aceito com ressalvas — prazo de correcao acordado",
                    "Recusado — unidade nao conforme",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Decisao formal do comprador sobre o recebimento da unidade.",
            },
        ],
        "secoes_obrigatorias": [
            "Conformidade Tecnica",
            "Vistoria por Comodo",
            "Instalacoes Eletricas",
            "Acabamentos",
            "Nao Conformidades",
            "Garantias",
            "Conclusao da Entrega",
        ],
    },

    # TVI-04 — Recebimento de Imovel
    {
        "id": "TVI-04",
        "nome": "Vistoria de Recebimento de Imovel",
        "ramo": "GERAL",
        "aplicacao": "Registro formal do estado do imovel no ato do recebimento, comparando com vistoria "
                     "anterior de entrega, coletando leituras de medidores e documentos recebidos.",
        "normas": [
            "Lei 8.245/1991 — Locacoes urbanas",
            "CC/2002 Art. 1.196 — Posse",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "rec04_comparativo_anterior",
                "secao": "Comparativo",
                "tipo": "select",
                "label": "Comparativo com Vistoria de Entrega Anterior",
                "opcoes": [
                    "Conforme — estado igual ao registrado na entrega",
                    "Melhorias realizadas — estado superior a entrega",
                    "Deterioracao por uso normal — esperada",
                    "Deterioracao acima do normal — danos a apurar",
                    "Sem vistoria anterior para comparacao",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Avalie o estado atual em relacao ao registrado na ultima vistoria.",
            },
            {
                "id": "rec04_leituras_medidores",
                "secao": "Medidores",
                "tipo": "tabela",
                "label": "Leituras de Medidores",
                "opcoes": ["Medidor", "Unidade", "Leitura atual", "Leitura anterior", "Consumo periodo"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Registre as leituras de todos os medidores: agua (m3), energia (kWh), gas (m3).",
            },
            {
                "id": "rec04_chaves_recebidas_qtd",
                "secao": "Chaves e Documentos",
                "tipo": "number",
                "label": "Quantidade de Chaves Recebidas",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 4",
                "ajuda": "Quantidade total de chaves/controles recebidos no ato.",
            },
            {
                "id": "rec04_documentos_entregues",
                "secao": "Chaves e Documentos",
                "tipo": "multiselect",
                "label": "Documentos Entregues",
                "opcoes": [
                    "Habite-se original",
                    "Manual do proprietario",
                    "Plantas do imovel",
                    "ART/TRT de construcao",
                    "Escritura publica",
                    "Copia da matricula",
                    "IPTU do exercicio",
                    "Apolice de seguro vigente",
                    "Regulamento interno do condominio",
                ],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Marque todos os documentos fisicamente recebidos no ato.",
            },
            {
                "id": "rec04_pendencias_aceitas",
                "secao": "Pendencias",
                "tipo": "caixa_texto",
                "label": "Pendencias Formalmente Aceitas",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva as pendencias aceitas com prazo de resolucao...",
                "ajuda": "Liste as pendencias que o recebedor aceita com prazo acordado para resolucao.",
            },
            {
                "id": "rec04_prazo_solucao_pendencias",
                "secao": "Pendencias",
                "tipo": "text",
                "label": "Prazo para Solucao das Pendencias",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 30 dias a partir do recebimento",
                "ajuda": "Prazo acordado entre as partes para resolucao das pendencias.",
            },
        ],
        "secoes_obrigatorias": [
            "Comparativo",
            "Medidores",
            "Chaves e Documentos",
            "Pendencias",
        ],
    },

    # TVI-05 — Conservacao Predial
    {
        "id": "TVI-05",
        "nome": "Vistoria de Conservacao Predial",
        "ramo": "GERAL",
        "aplicacao": "Avaliacao periodica do estado de conservacao do imovel conforme plano de manutencao "
                     "NBR 5674, verificando sistemas construtivos e identificando itens vencidos.",
        "normas": [
            "NBR 5674:2012 — Manutencao de edificacoes",
            "NBR 15575:2013 — Desempenho de edificacoes",
            "NBR 16280:2015 — Sistema de manutencao",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "cons05_periodicidade",
                "secao": "Identificacao da Vistoria",
                "tipo": "select",
                "label": "Periodicidade desta Vistoria",
                "opcoes": ["Mensal", "Trimestral", "Semestral", "Anual", "Bienal", "Sob demanda"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Periodicidade conforme Plano de Manutencao da edificacao.",
            },
            {
                "id": "cons05_historico_manutencoes",
                "secao": "Historico",
                "tipo": "tabela",
                "label": "Historico de Manutencoes Realizadas",
                "opcoes": ["Data", "Sistema", "Servico executado", "Empresa/Responsavel", "ART/Nota fiscal", "Proximo prazo"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste as manutencoes realizadas desde a ultima vistoria.",
            },
            {
                "id": "cons05_sistema_preventivo",
                "secao": "Plano de Manutencao",
                "tipo": "caixa_texto",
                "label": "Sistema de Manutencao Preventiva Adotado",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva o programa de manutencao preventiva vigente...",
                "ajuda": "Descreva o sistema preventivo conforme NBR 5674 (rotineira, preventiva, corretiva).",
            },
            {
                "id": "cons05_vida_util_sistemas",
                "secao": "Avaliacao de Sistemas",
                "tipo": "tabela",
                "label": "Vida Util dos Principais Sistemas",
                "opcoes": ["Sistema", "Vida util estimada (anos)", "Idade atual (anos)", "Restante (anos)", "Estado"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Levante a vida util de cada sistema: cobertura, impermeabilizacao, elevadores, etc.",
            },
            {
                "id": "cons05_plano_nbr5674",
                "secao": "Plano de Manutencao",
                "tipo": "caixa_texto",
                "label": "Observacoes sobre o Plano NBR 5674",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: plano implementado, desatualizado, inexistente...",
                "ajuda": "Avalie a aderencia do edificio ao plano de manutencao conforme NBR 5674.",
            },
            {
                "id": "cons05_itens_vencidos",
                "secao": "Itens Criticos",
                "tipo": "multiselect",
                "label": "Itens com Prazo de Manutencao Vencido",
                "opcoes": [
                    "Para-raios — ART vencida",
                    "Elevadores — revisao vencida",
                    "Extintores — validade vencida",
                    "AVCB — vencido",
                    "Reservatorio de agua — limpeza vencida",
                    "Impermeabilizacao — prazo de garantia vencido",
                    "Revestimento de fachada — prazo vencido",
                    "Sistema de gas — revisao vencida",
                    "Nenhum item vencido",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque todos os itens cujo prazo de manutencao ou garantia esta vencido.",
            },
        ],
        "secoes_obrigatorias": [
            "Identificacao da Vistoria",
            "Historico",
            "Avaliacao de Sistemas",
            "Plano de Manutencao",
            "Itens Criticos",
        ],
    },

    # TVI-06 — Cautelar de Vizinhanca
    {
        "id": "TVI-06",
        "nome": "Vistoria Cautelar de Vizinhanca",
        "ramo": "GERAL",
        "aplicacao": "Documentacao tecnica do estado do imovel vizinho antes, durante e apos obras "
                     "proximas, catalogando fissuras pre-existentes e estabelecendo monitoramento.",
        "normas": [
            "NBR 6118:2014 — Projeto de estruturas de concreto",
            "NBR 8044:1983 — Projeto geotecnico",
            "CC/2002 Art. 1.277 — Direito de vizinhanca",
            "NR-18 — Seguranca no trabalho na construcao",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "caut06_obra_endereco_responsavel",
                "secao": "Identificacao da Obra",
                "tipo": "text",
                "label": "Obra Causadora — Endereco e Responsavel Tecnico",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: Rua das Flores, 200 — Construtora XYZ — CREA: 12345",
                "ajuda": "Identifique o endereco da obra causadora e o responsavel tecnico.",
            },
            {
                "id": "caut06_distancia_metros",
                "secao": "Identificacao da Obra",
                "tipo": "number",
                "label": "Distancia da Obra ao Imovel Vistoriado (metros)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 3.5",
                "ajuda": "Distancia medida entre a obra e a divisa/fachada do imovel.",
            },
            {
                "id": "caut06_tipo_fundacao_obra",
                "secao": "Identificacao da Obra",
                "tipo": "select",
                "label": "Tipo de Fundacao da Obra Vizinha",
                "opcoes": [
                    "Sapata isolada",
                    "Sapata corrida",
                    "Radier",
                    "Estaca helice continua",
                    "Estaca raiz",
                    "Estaca escavada",
                    "Tubulao",
                    "Nao informado",
                ],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Tipo de fundacao adotado na obra, conforme ART disponivel.",
            },
            {
                "id": "caut06_registro_fotografico_geo",
                "secao": "Documentacao",
                "tipo": "caixa_texto",
                "label": "Registro Fotografico Georreferenciado — Descricao",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Descreva o sistema de georreferenciamento das fotos (GPS, pontos fixos, etc.)...",
                "ajuda": "Registre o metodo utilizado para georreferenciar as fotos.",
            },
            {
                "id": "caut06_fissuras_pre_existentes",
                "secao": "Catalogacao de Fissuras",
                "tipo": "tabela",
                "label": "Fissuras Pre-Existentes Catalogadas",
                "opcoes": ["Codigo", "Local (ambiente/fachada)", "Abertura (mm)", "Direcao", "Comprimento (cm)", "Foto referencia"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Catalogue cada fissura pre-existente com localizacao, medicao e registro fotografico.",
            },
            {
                "id": "caut06_monitoramento_fases",
                "secao": "Monitoramento",
                "tipo": "tabela",
                "label": "Monitoramento por Fases (antes / durante / apos)",
                "opcoes": ["Fase", "Data", "Responsavel", "Instrumento", "Leitura", "Variacao", "Observacao"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Registre as medicoes de monitoramento em cada fase da obra.",
            },
            {
                "id": "caut06_numero_processo_judicial",
                "secao": "Dados Juridicos",
                "tipo": "text",
                "label": "Numero do Processo Judicial (se houver)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 0001234-56.2024.8.26.0001",
                "ajuda": "Numero do processo caso ja exista acao judicial relacionada.",
            },
        ],
        "secoes_obrigatorias": [
            "Identificacao da Obra",
            "Documentacao",
            "Catalogacao de Fissuras",
            "Monitoramento",
            "Dados Juridicos",
        ],
    },

    # TVI-07 — Pre-Ocupacao
    {
        "id": "TVI-07",
        "nome": "Vistoria Pre-Ocupacao",
        "ramo": "GERAL",
        "aplicacao": "Verificacao tecnica do imovel imediatamente antes da ocupacao, validando habite-se, "
                     "ligacoes definitivas e conformidade com NBR 9050 (acessibilidade).",
        "normas": [
            "NBR 9050:2020 — Acessibilidade",
            "NBR 15575:2013 — Desempenho",
            "Lei Municipal de Uso e Ocupacao do Solo",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "preocp07_habite_se",
                "secao": "Documentacao Legal",
                "tipo": "checkbox",
                "label": "Habite-se / Auto de Conclusao Emitido",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Confirme a emissao do habite-se pela prefeitura antes da ocupacao.",
            },
            {
                "id": "preocp07_conformidade_projeto",
                "secao": "Conformidade Tecnica",
                "tipo": "select",
                "label": "Conformidade com Projeto Aprovado",
                "opcoes": [
                    "Totalmente conforme",
                    "Conforme com pequenas divergencias toleradas",
                    "Divergencias que exigem regularizacao",
                    "Nao conforme — ocupacao nao recomendada",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Avalie se o imovel construido corresponde ao projeto aprovado na prefeitura.",
            },
            {
                "id": "preocp07_alvara_funcionamento",
                "secao": "Documentacao Legal",
                "tipo": "text",
                "label": "Numero do Alvara de Funcionamento (uso nao residencial)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: AF-2024-00123",
                "ajuda": "Para uso comercial, informe o numero do alvara de funcionamento.",
            },
            {
                "id": "preocp07_ligacoes_definitivas",
                "secao": "Ligacoes e Servicos",
                "tipo": "multiselect",
                "label": "Ligacoes Definitivas Verificadas",
                "opcoes": [
                    "Agua — ligacao definitiva concluida",
                    "Energia eletrica — ligacao definitiva concluida",
                    "Gas — ligacao definitiva concluida",
                    "Esgoto — ligado a rede publica",
                    "Telefonia/Internet — infraestrutura instalada",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque todas as ligacoes definitivas ja concluidas.",
            },
            {
                "id": "preocp07_acessibilidade_nbr9050",
                "secao": "Acessibilidade",
                "tipo": "caixa_texto",
                "label": "Avaliacao de Acessibilidade (NBR 9050:2020)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva as condicoes de acessibilidade verificadas...",
                "ajuda": "Verifique: rampas, corrimaos, largura de circulacao, vagas PCD, banheiro adaptado.",
            },
            {
                "id": "preocp07_avcb",
                "secao": "Documentacao Legal",
                "tipo": "text",
                "label": "AVCB — Auto de Vistoria do Corpo de Bombeiros",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Numero do AVCB ou 'nao exigivel para este tipo de uso'",
                "ajuda": "Informe o numero do AVCB vigente ou justifique a dispensa.",
            },
        ],
        "secoes_obrigatorias": [
            "Documentacao Legal",
            "Conformidade Tecnica",
            "Ligacoes e Servicos",
            "Acessibilidade",
        ],
    },

    # TVI-08 — Pos-Ocupacao
    {
        "id": "TVI-08",
        "nome": "Vistoria Pos-Ocupacao",
        "ramo": "GERAL",
        "aplicacao": "Avaliacao tecnica do imovel apos periodo de uso, identificando desgastes naturais, "
                     "danos indevidos, reformas realizadas e comparando com o estado de entrega.",
        "normas": [
            "NBR 15575:2013 — Desempenho",
            "CC/2002 Art. 569 — Obrigacoes do locatario",
            "Lei 8.245/1991 Art. 23 — Deveres do locatario",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "posoc08_tempo_ocupacao",
                "secao": "Dados da Ocupacao",
                "tipo": "text",
                "label": "Tempo de Ocupacao",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 3 anos e 4 meses",
                "ajuda": "Periodo total de ocupacao do imovel ate a data da vistoria.",
            },
            {
                "id": "posoc08_numero_ocupantes",
                "secao": "Dados da Ocupacao",
                "tipo": "number",
                "label": "Numero Medio de Ocupantes",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 4",
                "ajuda": "Quantidade media de pessoas que habitaram o imovel.",
            },
            {
                "id": "posoc08_uso_conforme",
                "secao": "Dados da Ocupacao",
                "tipo": "select",
                "label": "Uso do Imovel Conforme / Diferente do Previsto",
                "opcoes": [
                    "Conforme — uso residencial unifamiliar",
                    "Conforme — uso comercial autorizado",
                    "Diferente — uso misto nao autorizado",
                    "Diferente — uso comercial em imovel residencial",
                    "Diferente — sublocacao parcial",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Indique se o uso do imovel foi conforme o contratado.",
            },
            {
                "id": "posoc08_desgaste_identificado",
                "secao": "Estado de Conservacao",
                "tipo": "caixa_texto",
                "label": "Desgaste Natural Identificado",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Descreva os desgastes naturais por uso, por ambiente...",
                "ajuda": "Liste os desgastes naturais decorrentes do uso normal e do tempo.",
            },
            {
                "id": "posoc08_reformas_realizadas",
                "secao": "Reformas",
                "tipo": "tabela",
                "label": "Reformas Realizadas pelo Ocupante",
                "opcoes": ["Descricao da reforma", "Ambiente", "Data aprox.", "Autorizacao do locador", "Reversivel"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Registre cada reforma feita pelo ocupante durante o periodo.",
            },
            {
                "id": "posoc08_comparativo_entrega",
                "secao": "Comparativo",
                "tipo": "select",
                "label": "Comparativo com Estado de Entrega",
                "opcoes": [
                    "Estado superior ao da entrega",
                    "Estado identico ao da entrega",
                    "Desgaste natural esperado",
                    "Deterioracao acima do normal — danos imputaveis",
                    "Sem vistoria de entrega para comparacao",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Comparacao global com o estado documentado na vistoria de entrega.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados da Ocupacao",
            "Estado de Conservacao",
            "Reformas",
            "Comparativo",
        ],
    },
]
