# @module seed_tvi — Modelos TVI Ramos 2-3: LOCACAO (TVI-09 a TVI-12) + RURAL (TVI-13 a TVI-18)
"""
Modelos profissionais dos Ramos LOCACAO e RURAL com novo schema unificado.
Cada campo possui id EXCLUSIVO — nenhum campo e compartilhado entre modelos.
Schema: {id, nome, ramo, aplicacao, normas, requer_art, campos_especificos, secoes_obrigatorias}
"""

MODELOS_LOCACAO = [
    # TVI-09 — Entrada Locacao
    {
        "id": "TVI-09",
        "nome": "Vistoria de Entrada — Locacao",
        "ramo": "LOCACAO",
        "aplicacao": "Registro detalhado do estado do imovel no inicio do contrato de locacao, "
                     "documentando medidores, mobilia, chaves e estado de cada comodo.",
        "normas": [
            "Lei 8.245/1991 — Locacoes urbanas",
            "CC/2002 Art. 567 — Conservacao da coisa",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "loc09_numero_contrato",
                "secao": "Dados do Contrato",
                "tipo": "text",
                "label": "Numero do Contrato de Locacao",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: LOC-2024-00123",
                "ajuda": "Numero ou identificador do contrato de locacao.",
            },
            {
                "id": "loc09_valor_aluguel",
                "secao": "Dados do Contrato",
                "tipo": "number",
                "label": "Valor do Aluguel Mensal (R$)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 2500.00",
                "ajuda": "Valor mensal do aluguel conforme contrato.",
            },
            {
                "id": "loc09_indice_reajuste",
                "secao": "Dados do Contrato",
                "tipo": "select",
                "label": "Indice de Reajuste",
                "opcoes": ["IGP-M", "IPCA", "INPC", "IPC-A", "IVAR/FGV", "Negociado entre partes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Indice de reajuste anual previsto no contrato.",
            },
            {
                "id": "loc09_leituras_medidores_entrada",
                "secao": "Medidores",
                "tipo": "tabela",
                "label": "Leituras de Medidores na Entrada",
                "opcoes": ["Medidor", "Numero/Codigo", "Leitura (valor + unidade)", "Data leitura", "Foto"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Registre agua (m3), energia (kWh) e gas (m3) com numero do medidor.",
            },
            {
                "id": "loc09_estado_por_comodo",
                "secao": "Estado por Comodo",
                "tipo": "tabela",
                "label": "Estado do Imovel por Comodo",
                "opcoes": ["Comodo", "Nota (otimo/bom/regular/ruim)", "Piso", "Parede", "Teto", "Observacoes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Avalie cada comodo com nota e descricao das condicoes.",
            },
            {
                "id": "loc09_chaves_quantidade",
                "secao": "Chaves e Controles",
                "tipo": "number",
                "label": "Quantidade de Chaves Entregues",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 3",
                "ajuda": "Total de chaves e controles de acesso entregues ao locatario.",
            },
            {
                "id": "loc09_mobilia_inventario_entrada",
                "secao": "Mobilia",
                "tipo": "tabela",
                "label": "Inventario de Mobilia e Equipamentos",
                "opcoes": ["Item", "Localizacao", "Estado", "Observacoes"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste cada item de mobilia ou equipamento com estado de conservacao.",
            },
            {
                "id": "loc09_prazo_contrato_meses",
                "secao": "Dados do Contrato",
                "tipo": "number",
                "label": "Prazo do Contrato (meses)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 30",
                "ajuda": "Duracao total do contrato de locacao em meses.",
            },
            {
                "id": "loc09_garantia_tipo",
                "secao": "Dados do Contrato",
                "tipo": "select",
                "label": "Tipo de Garantia Locaticia",
                "opcoes": [
                    "Fiador/Fianca pessoal",
                    "Seguro fianca",
                    "Deposito caucao",
                    "Titulo de capitalizacao",
                    "Cessao fiduciaria de quotas",
                    "Sem garantia",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Modalidade de garantia prevista no contrato conforme Lei 8.245/1991.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados do Contrato",
            "Medidores",
            "Estado por Comodo",
            "Chaves e Controles",
            "Mobilia",
        ],
    },

    # TVI-10 — Saida Locacao
    {
        "id": "TVI-10",
        "nome": "Vistoria de Saida — Locacao",
        "ramo": "LOCACAO",
        "aplicacao": "Registro do estado do imovel ao termino da locacao, comparando com a vistoria de "
                     "entrada, apurando danos imputaveis e calculando estimativa de reparos.",
        "normas": [
            "Lei 8.245/1991 Art. 23 — Deveres do locatario",
            "Sumula 259 do STJ — danos e desgaste natural",
            "CC/2002 Art. 584 — Devolucao da coisa",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "sai10_comparativo_entrada_saida",
                "secao": "Comparativo",
                "tipo": "select",
                "label": "Resultado Comparativo Entrada vs. Saida",
                "opcoes": [
                    "Imovel devolvido em estado equivalente ou melhor",
                    "Desgaste natural — sem ressarcimento",
                    "Danos imputaveis ao locatario — ressarcimento parcial",
                    "Danos imputaveis ao locatario — ressarcimento integral",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Resultado global do comparativo entre as vistorias de entrada e saida.",
            },
            {
                "id": "sai10_leituras_finais",
                "secao": "Medidores",
                "tipo": "tabela",
                "label": "Leituras Finais de Medidores",
                "opcoes": ["Medidor", "Leitura final", "Leitura entrada", "Consumo total", "Unidade"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Registre as leituras finais e calcule o consumo total do periodo.",
            },
            {
                "id": "sai10_danos_imputaveis",
                "secao": "Apuracao de Danos",
                "tipo": "tabela",
                "label": "Danos Imputaveis ao Locatario",
                "opcoes": ["Item danificado", "Ambiente", "Descricao do dano", "Custo estimado (R$)", "Foto ref."],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste item a item os danos que vao alem do desgaste natural.",
            },
            {
                "id": "sai10_danos_desgaste_natural",
                "secao": "Apuracao de Danos",
                "tipo": "caixa_texto",
                "label": "Danos por Desgaste Natural — Sem Imputacao",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva os danos considerados desgaste natural de uso...",
                "ajuda": "Registre os itens danificados que sao atribuidos ao uso normal do imovel.",
            },
            {
                "id": "sai10_estimativa_reparos_total",
                "secao": "Apuracao de Danos",
                "tipo": "number",
                "label": "Estimativa Total de Reparos Imputaveis (R$)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 3500.00",
                "ajuda": "Soma total dos custos estimados dos danos imputaveis ao locatario.",
            },
            {
                "id": "sai10_itens_devolvidos_faltantes",
                "secao": "Inventario Final",
                "tipo": "caixa_texto",
                "label": "Itens Devolvidos / Faltantes (Mobilia e Chaves)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: devolucao: 2 chaves / faltante: 1 controle garagem, mesa da sala...",
                "ajuda": "Relacione o que foi devolvido e o que esta faltando em relacao ao inventario de entrada.",
            },
            {
                "id": "sai10_prazo_devolucao_deposito",
                "secao": "Encerramento Contratual",
                "tipo": "text",
                "label": "Prazo para Devolucao do Deposito/Caucao",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 30 dias apos a entrega das chaves",
                "ajuda": "Prazo acordado entre as partes para a devolucao do deposito caucao.",
            },
            {
                "id": "sai10_parecer_saida",
                "secao": "Encerramento Contratual",
                "tipo": "select",
                "label": "Parecer Final da Vistoria de Saida",
                "opcoes": [
                    "Aceito — imovel devolvido em boas condicoes",
                    "Aceito com ressalvas — desconto negociado",
                    "Recusado — danos nao quitados",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Conclusao formal da vistoria de saida.",
            },
        ],
        "secoes_obrigatorias": [
            "Comparativo",
            "Medidores",
            "Apuracao de Danos",
            "Inventario Final",
            "Encerramento Contratual",
        ],
    },

    # TVI-11 — Renovacao Contratual
    {
        "id": "TVI-11",
        "nome": "Vistoria de Renovacao Contratual — Locacao",
        "ramo": "LOCACAO",
        "aplicacao": "Vistoria realizada por ocasiao da renovacao do contrato de locacao, avaliando "
                     "o estado atual do imovel, aditivos anteriores e novas condicoes pactuadas.",
        "normas": [
            "Lei 8.245/1991 Art. 51 — Renovacao compulsoria",
            "CC/2002 Art. 575 — Prazo de locacao",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "ren11_contrato_original_numero",
                "secao": "Historico Contratual",
                "tipo": "text",
                "label": "Numero do Contrato Original",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: LOC-2021-00045",
                "ajuda": "Numero do contrato original que esta sendo renovado.",
            },
            {
                "id": "ren11_aditivos_anteriores",
                "secao": "Historico Contratual",
                "tipo": "caixa_texto",
                "label": "Aditivos Anteriores (resumo)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 1o aditivo — jan/2023 — reajuste IPCA 5,8%; 2o aditivo — jul/2023 — prazo...",
                "ajuda": "Resuma os aditivos formalizados durante o periodo contratual.",
            },
            {
                "id": "ren11_estado_atual_vs_entrada",
                "secao": "Estado do Imovel",
                "tipo": "select",
                "label": "Estado Atual vs. Vistoria de Entrada",
                "opcoes": [
                    "Estado superior ao da entrada",
                    "Estado equivalente ao da entrada",
                    "Desgaste natural compativel com o periodo",
                    "Deterioracao acima do esperado",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Avaliacao comparativa do estado atual em relacao ao registrado na entrada.",
            },
            {
                "id": "ren11_manutencoes_locatario",
                "secao": "Estado do Imovel",
                "tipo": "tabela",
                "label": "Manutencoes Realizadas pelo Locatario",
                "opcoes": ["Descricao", "Ambiente", "Periodo", "Custo aprox.", "Autorizacao"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste as manutencoes feitas pelo locatario durante o contrato.",
            },
            {
                "id": "ren11_pendencias_locador",
                "secao": "Pendencias",
                "tipo": "caixa_texto",
                "label": "Pendencias de Responsabilidade do Locador",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: reparo no telhado, pintura de fachada...",
                "ajuda": "Relacione as pendencias que sao de responsabilidade do proprietario.",
            },
            {
                "id": "ren11_novo_valor_aluguel",
                "secao": "Novas Condicoes",
                "tipo": "number",
                "label": "Novo Valor do Aluguel (R$)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 2800.00",
                "ajuda": "Valor do aluguel acordado para o novo periodo contratual.",
            },
            {
                "id": "ren11_indice_reajuste_renovacao",
                "secao": "Novas Condicoes",
                "tipo": "select",
                "label": "Indice de Reajuste na Renovacao",
                "opcoes": ["IGP-M", "IPCA", "INPC", "IPC-A", "IVAR/FGV", "Negociado entre partes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Indice de reajuste definido para o contrato renovado.",
            },
        ],
        "secoes_obrigatorias": [
            "Historico Contratual",
            "Estado do Imovel",
            "Pendencias",
            "Novas Condicoes",
        ],
    },

    # TVI-12 — Periodica Locacao
    {
        "id": "TVI-12",
        "nome": "Vistoria Periodica — Locacao",
        "ramo": "LOCACAO",
        "aplicacao": "Vistoria de acompanhamento durante a vigencia do contrato de locacao, verificando "
                     "conservacao, uso adequado e cumprimento das obrigacoes contratuais.",
        "normas": [
            "Lei 8.245/1991 Art. 23 — Deveres do locatario",
            "CC/2002 Art. 569 — Uso conforme destinacao",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "per12_numero_vistoria_seq",
                "secao": "Identificacao",
                "tipo": "number",
                "label": "Numero Sequencial desta Vistoria",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 3 (terceira vistoria periodica)",
                "ajuda": "Numero de ordem desta vistoria na sequencia do contrato.",
            },
            {
                "id": "per12_ocorrencias_desde_ultima",
                "secao": "Ocorrencias",
                "tipo": "caixa_texto",
                "label": "Ocorrencias Desde a Ultima Vistoria",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva incidentes, reparos, notificacoes ou reclamacoes...",
                "ajuda": "Registre tudo o que ocorreu relevante ao imovel desde a vistoria anterior.",
            },
            {
                "id": "per12_uso_adequado",
                "secao": "Conformidade de Uso",
                "tipo": "select",
                "label": "Uso Adequado conforme Contrato",
                "opcoes": [
                    "Uso adequado — conforme contrato",
                    "Uso parcialmente adequado — advertencia emitida",
                    "Uso inadequado — notificacao formal",
                    "Uso inadequado — rescisao recomendada",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Avalie se o imovel esta sendo utilizado conforme a finalidade contratada.",
            },
            {
                "id": "per12_sublocacao",
                "secao": "Conformidade de Uso",
                "tipo": "checkbox",
                "label": "Sublocacao Identificada (nao autorizada)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Marque se identificou sublocacao total ou parcial nao autorizada pelo locador.",
            },
            {
                "id": "per12_notificacoes_emitidas",
                "secao": "Acoes",
                "tipo": "caixa_texto",
                "label": "Notificacoes Emitidas",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva as notificacoes formais emitidas ao locatario...",
                "ajuda": "Registre o teor e a data das notificacoes emitidas nesta vistoria.",
            },
        ],
        "secoes_obrigatorias": [
            "Identificacao",
            "Ocorrencias",
            "Conformidade de Uso",
            "Acoes",
        ],
    },
]

MODELOS_RURAL = [
    # TVI-13 — Rural Caracterizacao
    {
        "id": "TVI-13",
        "nome": "Vistoria Rural — Caracterizacao Tecnica",
        "ramo": "RURAL",
        "aplicacao": "Caracterizacao tecnica completa de imovel rural: documentacao fundiaria, benfeitorias, "
                     "recursos naturais, uso do solo, reserva legal e conformidade ambiental.",
        "normas": [
            "Lei 4.504/1964 — Estatuto da Terra",
            "Lei 12.651/2012 — Codigo Florestal",
            "IN INCRA 11/2003 — Caracterizacao do imovel rural",
            "NBR 14653-3:2019 — Avaliacao de imoveis rurais",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "rur13_ccir",
                "secao": "Documentacao Fundiaria",
                "tipo": "text",
                "label": "CCIR — Certificado de Cadastro de Imovel Rural",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 1234567890123",
                "ajuda": "Numero do CCIR emitido pelo INCRA.",
            },
            {
                "id": "rur13_nif_cib",
                "secao": "Documentacao Fundiaria",
                "tipo": "text",
                "label": "NIF / CIB (Numero no INCRA)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: CIB 12345678901",
                "ajuda": "Numero de Identificacao do Imovel ou Codigo do Imovel Beneficiario.",
            },
            {
                "id": "rur13_itr_situacao",
                "secao": "Documentacao Fundiaria",
                "tipo": "select",
                "label": "Situacao do ITR",
                "opcoes": [
                    "Em dia — ultima declaracao aprovada",
                    "Declaracao pendente",
                    "Debito em aberto",
                    "Isento (modulo fiscal ate 1)",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao fiscal do Imposto Territorial Rural.",
            },
            {
                "id": "rur13_area_total_vs_medida",
                "secao": "Caracterizacao da Area",
                "tipo": "number",
                "label": "Diferenca Area Registrada vs. Area Medida (ha)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 2.45 (positivo = medida maior)",
                "ajuda": "Diferenca entre a area constante no CCIR/matricula e a area medida in loco.",
            },
            {
                "id": "rur13_modulo_fiscal",
                "secao": "Caracterizacao da Area",
                "tipo": "number",
                "label": "Modulo Fiscal do Municipio (ha)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 18.0",
                "ajuda": "Valor do modulo fiscal vigente para o municipio de localizacao do imovel.",
            },
            {
                "id": "rur13_fracao_minima",
                "secao": "Caracterizacao da Area",
                "tipo": "number",
                "label": "Fracao Minima de Parcelamento (ha)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 3.6",
                "ajuda": "Fracao minima de parcelamento definida para o municipio.",
            },
            {
                "id": "rur13_gut_percentual",
                "secao": "Caracterizacao da Area",
                "tipo": "number",
                "label": "GUT — Grau de Utilizacao da Terra (%)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 75.5",
                "ajuda": "Percentual de utilizacao efetiva do imovel rural conforme IN INCRA.",
            },
            {
                "id": "rur13_gee_percentual",
                "secao": "Caracterizacao da Area",
                "tipo": "number",
                "label": "GEE — Grau de Eficiencia na Exploracao (%)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 100.0",
                "ajuda": "Percentual de eficiencia na exploracao conforme indices INCRA.",
            },
            {
                "id": "rur13_benfeitorias",
                "secao": "Benfeitorias",
                "tipo": "tabela",
                "label": "Benfeitorias Rurais",
                "opcoes": ["Tipo de benfeitoria", "Descricao", "Estado de conservacao", "Valor estimado (R$)"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste todas as benfeitorias: casa sede, silos, currais, armazens, etc.",
            },
            {
                "id": "rur13_recursos_hidricos",
                "secao": "Recursos Naturais",
                "tipo": "multiselect",
                "label": "Recursos Hidricos Identificados",
                "opcoes": [
                    "Rio/corrego perene",
                    "Rio/corrego intermitente",
                    "Nacente",
                    "Lagoa/acude",
                    "Poco artesiano",
                    "Poco comum",
                    "Canal de irrigacao",
                    "Sem recursos hidricos significativos",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque todos os recursos hidricos presentes no imovel.",
            },
            {
                "id": "rur13_solo_topografia",
                "secao": "Recursos Naturais",
                "tipo": "caixa_texto",
                "label": "Solo e Topografia",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: solo argiloso, relevo plano a suavemente ondulado, boa fertilidade...",
                "ajuda": "Descreva o tipo de solo e o relevo do imovel.",
            },
            {
                "id": "rur13_cultura_explorada",
                "secao": "Uso do Solo",
                "tipo": "caixa_texto",
                "label": "Cultura / Atividade Explorada",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: pecuaria bovina extensiva, soja/milho em rotacao...",
                "ajuda": "Descreva a atividade agropecuaria ou florestal explorada.",
            },
            {
                "id": "rur13_reserva_legal_percentual",
                "secao": "Conformidade Ambiental",
                "tipo": "number",
                "label": "Reserva Legal Declarada (%)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 20.0 (minimo legal para Cerrado fora da Amazonia)",
                "ajuda": "Percentual de reserva legal declarada no CAR.",
            },
            {
                "id": "rur13_apps_identificadas",
                "secao": "Conformidade Ambiental",
                "tipo": "caixa_texto",
                "label": "Areas de Preservacao Permanente (APPs)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: APP de curso dagua — 30m / APP de nascente — 50m raio...",
                "ajuda": "Descreva as APPs identificadas no imovel conforme Codigo Florestal.",
            },
        ],
        "secoes_obrigatorias": [
            "Documentacao Fundiaria",
            "Caracterizacao da Area",
            "Benfeitorias",
            "Recursos Naturais",
            "Uso do Solo",
            "Conformidade Ambiental",
        ],
    },

    # TVI-14 — Georreferenciamento
    {
        "id": "TVI-14",
        "nome": "Vistoria de Georreferenciamento Rural",
        "ramo": "RURAL",
        "aplicacao": "Vistoria para fins de georreferenciamento de imovel rural conforme normas INCRA, "
                     "com levantamento de vertices, confrontantes e elaboracao de memorial descritivo.",
        "normas": [
            "Decreto 4.449/2002 — Georreferenciamento de imoveis rurais",
            "IN INCRA 77/2013 — Normas tecnicas de georreferenciamento",
            "SIRGAS 2000 — Sistema de Referencia Geodesico",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "geo14_codigo_sigef",
                "secao": "Identificacao SIGEF",
                "tipo": "text",
                "label": "Codigo SIGEF do Imovel",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: BR-AA-1234567-A",
                "ajuda": "Codigo de identificacao do imovel no SIGEF/INCRA.",
            },
            {
                "id": "geo14_datum_sirgas2000",
                "secao": "Dados Geodesicos",
                "tipo": "text",
                "label": "Sistema Geodesico (Datum)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "SIRGAS 2000",
                "ajuda": "Sistema de Referencia Geocentrico para as Americas (SIRGAS 2000).",
            },
            {
                "id": "geo14_numero_vertices",
                "secao": "Dados Geodesicos",
                "tipo": "number",
                "label": "Numero de Vertices do Perimetro",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 12",
                "ajuda": "Quantidade total de vertices que definem o perimetro do imovel.",
            },
            {
                "id": "geo14_metodo_levantamento",
                "secao": "Dados Geodesicos",
                "tipo": "select",
                "label": "Metodo de Levantamento",
                "opcoes": [
                    "GPS RTK (Real Time Kinematic)",
                    "GNSS com processamento pos-cargado",
                    "Estacao Total com rastreio geodesico",
                    "LIDAR aereo",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Metodo utilizado para determinar as coordenadas dos vertices.",
            },
            {
                "id": "geo14_precisao_metros",
                "secao": "Dados Geodesicos",
                "tipo": "number",
                "label": "Precisao do Levantamento (metros)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 0.50",
                "ajuda": "Precisao maxima do levantamento conforme IN INCRA (0,50m para Classe A).",
            },
            {
                "id": "geo14_confrontantes_tabela",
                "secao": "Confrontantes",
                "tipo": "tabela",
                "label": "Confrontantes do Imovel",
                "opcoes": ["Nome do confrontante", "Matricula", "Lado (N/S/L/O)", "Anuencia (sim/nao/pendente)", "Observacoes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Liste todos os confrontantes com anuencia ou justificativa de dispensa.",
            },
            {
                "id": "geo14_memorial_descritivo",
                "secao": "Documentos Tecnicos",
                "tipo": "caixa_texto",
                "label": "Memorial Descritivo do Perimetro",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Insira o memorial descritivo conforme norma INCRA...",
                "ajuda": "Memorial descritivo completo com coordenadas e azimutes de cada vertice.",
            },
            {
                "id": "geo14_art_levantamento",
                "secao": "Responsabilidade Tecnica",
                "tipo": "text",
                "label": "ART do Levantamento Geodesico",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: ART CREA 2024-654321-0",
                "ajuda": "ART emitida pelo engenheiro agrimensor responsavel pelo levantamento.",
            },
            {
                "id": "geo14_situacao_sigef",
                "secao": "Identificacao SIGEF",
                "tipo": "select",
                "label": "Situacao no SIGEF",
                "opcoes": [
                    "Em analise",
                    "Certificado",
                    "Aguardando anuencia de confrontante",
                    "Com inconsistencias — retrabalho",
                    "Cancelado",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao atual do processo de certificacao no SIGEF.",
            },
        ],
        "secoes_obrigatorias": [
            "Identificacao SIGEF",
            "Dados Geodesicos",
            "Confrontantes",
            "Documentos Tecnicos",
            "Responsabilidade Tecnica",
        ],
    },

    # TVI-15 — Confrontacao Rural
    {
        "id": "TVI-15",
        "nome": "Vistoria de Confrontacao Rural",
        "ramo": "RURAL",
        "aplicacao": "Identificacao e registro dos confrontantes do imovel rural, verificando marcos fisicos, "
                     "divergencias de limites, posseiros e conflitos fundiarios.",
        "normas": [
            "Lei 6.015/1973 — Registros Publicos",
            "IN INCRA 77/2013",
            "CC/2002 Art. 1.297 — Direito de cercar",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "conf15_confrontantes_tabela",
                "secao": "Confrontantes",
                "tipo": "tabela",
                "label": "Relacao de Confrontantes",
                "opcoes": ["Nome/Razao social", "Matricula do imovel vizinho", "Lado (N/S/L/O)", "Extensao (m)", "Observacoes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Liste todos os confrontantes com matricula e extensao de cada divisa.",
            },
            {
                "id": "conf15_marcos_fisicos",
                "secao": "Marcos e Limites",
                "tipo": "tabela",
                "label": "Marcos Fisicos do Perimetro",
                "opcoes": ["Codigo do marco", "Tipo (pino/moirao/pedra)", "Coordenadas (Lat/Long)", "Estado de conservacao"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Registre cada marco fisico com tipo, coordenadas e estado.",
            },
            {
                "id": "conf15_divergencias_limites",
                "secao": "Conflitos",
                "tipo": "caixa_texto",
                "label": "Divergencias de Limites Identificadas",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva as sobreposicoes, faltas ou desvios de divisas...",
                "ajuda": "Registre qualquer divergencia entre os limites documentais e os fisicos.",
            },
            {
                "id": "conf15_posseiros_invasoes",
                "secao": "Conflitos",
                "tipo": "caixa_texto",
                "label": "Posseiros / Invasoes Identificadas",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva areas com presenca de terceiros sem titulo...",
                "ajuda": "Informe se ha posseiros ou invasores com descricao da situacao.",
            },
            {
                "id": "conf15_anuencias_obtidas",
                "secao": "Documentacao",
                "tipo": "caixa_texto",
                "label": "Anuencias Obtidas / Pendentes",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: confrontante Norte assinou; confrontante Sul — localizacao pendente...",
                "ajuda": "Informe o status das anuencias de cada confrontante.",
            },
            {
                "id": "conf15_conflitos_fundiarios",
                "secao": "Conflitos",
                "tipo": "caixa_texto",
                "label": "Conflitos Fundiarios",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva disputas ou acoes judiciais sobre os limites...",
                "ajuda": "Registre conflitos fundiarios existentes que afetam os limites do imovel.",
            },
        ],
        "secoes_obrigatorias": [
            "Confrontantes",
            "Marcos e Limites",
            "Conflitos",
            "Documentacao",
        ],
    },

    # TVI-16 — Uso do Solo Rural
    {
        "id": "TVI-16",
        "nome": "Vistoria de Uso e Ocupacao do Solo Rural",
        "ramo": "RURAL",
        "aplicacao": "Levantamento do uso e ocupacao do solo em imovel rural, verificando zoneamento, "
                     "cobertura vegetal nativa, passivo ambiental e situacao CAR.",
        "normas": [
            "Lei 12.651/2012 — Codigo Florestal",
            "Decreto 7.830/2012 — SICAR",
            "IN MMA 02/2014 — Registro no CAR",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "uso16_zoneamento",
                "secao": "Caracterizacao do Uso",
                "tipo": "select",
                "label": "Zoneamento Agropecuario / Ecologico-Economico",
                "opcoes": [
                    "Zona Agricola — uso agricola permitido",
                    "Zona Pecuaria — pastagem permitida",
                    "Zona de Preservacao — restricao de uso",
                    "Zona de Extrativismo",
                    "Zona de Assentamento",
                    "Sem zoneamento definido",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Zoneamento ecologico-economico ou agrario aplicavel ao imovel.",
            },
            {
                "id": "uso16_uso_atual",
                "secao": "Caracterizacao do Uso",
                "tipo": "select",
                "label": "Uso Atual do Solo",
                "opcoes": [
                    "Lavoura temporaria",
                    "Lavoura permanente",
                    "Pastagem cultivada",
                    "Pastagem natural",
                    "Floresta nativa",
                    "Floresta plantada",
                    "Pousio",
                    "Uso misto",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Classificacao do uso atual conforme mapeamento de campo.",
            },
            {
                "id": "uso16_uso_permitido",
                "secao": "Caracterizacao do Uso",
                "tipo": "caixa_texto",
                "label": "Uso Permitido pela Legislacao Vigente",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva o uso permitido conforme zoneamento e codigo florestal...",
                "ajuda": "Descreva o que e permitido em cada porcao do imovel conforme a lei.",
            },
            {
                "id": "uso16_cobertura_vegetal_nativa",
                "secao": "Cobertura Vegetal",
                "tipo": "number",
                "label": "Cobertura Vegetal Nativa (%)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 22.0",
                "ajuda": "Percentual da area do imovel coberto por vegetacao nativa.",
            },
            {
                "id": "uso16_atividades_app_rl",
                "secao": "Cobertura Vegetal",
                "tipo": "caixa_texto",
                "label": "Atividades em APP e Reserva Legal",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: pastagem em APP de nascente, roçada em RL...",
                "ajuda": "Descreva atividades irregulares ou autorizadas em APP e RL.",
            },
            {
                "id": "uso16_passivo_ambiental",
                "secao": "Conformidade Ambiental",
                "tipo": "caixa_texto",
                "label": "Passivo Ambiental Identificado",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: deficit de RL de 5 ha, APP suprimida sem autorizacao...",
                "ajuda": "Descreva o passivo ambiental existente e pendencias de recuperacao.",
            },
            {
                "id": "uso16_car_situacao",
                "secao": "Conformidade Ambiental",
                "tipo": "select",
                "label": "Situacao do CAR (Cadastro Ambiental Rural)",
                "opcoes": [
                    "Ativo — cadastro aprovado",
                    "Ativo — em analise",
                    "Pendente de complementacao",
                    "Cancelado",
                    "Nao inscrito",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao atual do CAR no SICAR.",
            },
        ],
        "secoes_obrigatorias": [
            "Caracterizacao do Uso",
            "Cobertura Vegetal",
            "Conformidade Ambiental",
        ],
    },

    # TVI-17 — Retificacao de Area
    {
        "id": "TVI-17",
        "nome": "Vistoria de Retificacao de Area Rural",
        "ramo": "RURAL",
        "aplicacao": "Vistoria tecnica para subsidiar processo de retificacao de area em cartorio, "
                     "demonstrando a diferenca entre a area registrada e a area efetivamente medida.",
        "normas": [
            "Lei 6.015/1973 Art. 213 — Retificacao de registro",
            "NBR 13133:1994 — Execucao de levantamento topografico",
            "Provimento CNJ 150/2023 — Retificacao administrativa",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "ret17_area_registrada_ha",
                "secao": "Comparativo de Areas",
                "tipo": "number",
                "label": "Area Registrada na Matricula (ha)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 45.80",
                "ajuda": "Area constante na matricula do Registro de Imoveis.",
            },
            {
                "id": "ret17_area_medida_ha",
                "secao": "Comparativo de Areas",
                "tipo": "number",
                "label": "Area Medida no Levantamento (ha)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 47.35",
                "ajuda": "Area apurada no levantamento topografico realizado.",
            },
            {
                "id": "ret17_diferenca_ha",
                "secao": "Comparativo de Areas",
                "tipo": "number",
                "label": "Diferenca de Area (ha)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 1.55 (positivo = medida maior que registrada)",
                "ajuda": "Diferenca absoluta entre area registrada e area medida.",
            },
            {
                "id": "ret17_justificativa_tecnica",
                "secao": "Fundamentacao",
                "tipo": "caixa_texto",
                "label": "Justificativa Tecnica da Retificacao",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Explique a origem da discrepancia (erro historico de medicao, acrescimo de aluviao, etc.)...",
                "ajuda": "Justifique tecnicamente a origem da diferenca de area.",
            },
            {
                "id": "ret17_documentos_suporte",
                "secao": "Fundamentacao",
                "tipo": "multiselect",
                "label": "Documentos de Suporte",
                "opcoes": [
                    "Memorial descritivo com coordenadas",
                    "Planta topografica georreferenciada",
                    "ART do levantamento",
                    "Declaracao de confrontantes",
                    "Titulo de propriedade original",
                    "Historico de matricula",
                    "Fotos aereas / imagens de satelite",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Selecione todos os documentos que embasam o pedido de retificacao.",
            },
            {
                "id": "ret17_anuencia_confrontantes_ret",
                "secao": "Fundamentacao",
                "tipo": "caixa_texto",
                "label": "Anuencia dos Confrontantes",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: todos os confrontantes assinaram; confrontante Leste — dispensado...",
                "ajuda": "Informe o status das anuencias exigidas para a retificacao administrativa.",
            },
        ],
        "secoes_obrigatorias": [
            "Comparativo de Areas",
            "Fundamentacao",
        ],
    },

    # TVI-18 — Certificacao SIGEF
    {
        "id": "TVI-18",
        "nome": "Vistoria de Certificacao SIGEF/INCRA",
        "ramo": "RURAL",
        "aplicacao": "Vistoria e acompanhamento do processo de certificacao de imovel rural junto ao "
                     "SIGEF/INCRA, desde o protocolo ate a emissao do numero de certificacao.",
        "normas": [
            "Decreto 4.449/2002",
            "IN INCRA 77/2013 — Normas tecnicas SIGEF",
            "Resolucao CONFEA 1.094/2017 — ART",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "sigef18_codigo_processo",
                "secao": "Identificacao SIGEF",
                "tipo": "text",
                "label": "Codigo do Processo SIGEF",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: BR-PR-1234567-A",
                "ajuda": "Codigo do processo de certificacao no portal SIGEF.",
            },
            {
                "id": "sigef18_situacao",
                "secao": "Identificacao SIGEF",
                "tipo": "select",
                "label": "Situacao do Processo",
                "opcoes": [
                    "Em analise pelo INCRA",
                    "Aprovado — aguardando certificado",
                    "Certificado emitido",
                    "Rejeitado — pendencias a corrigir",
                    "Pendente de anuencia",
                    "Cancelado",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao atual do processo no SIGEF.",
            },
            {
                "id": "sigef18_codigo_incra_fqns",
                "secao": "Identificacao SIGEF",
                "tipo": "text",
                "label": "Codigo INCRA (FQNS)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 1234/5678/9012/3456",
                "ajuda": "Codigo INCRA no formato FQNS (Fazenda/Quadra/Nome/Situacao).",
            },
            {
                "id": "sigef18_pendencias_incra",
                "secao": "Pendencias",
                "tipo": "caixa_texto",
                "label": "Pendencias Apontadas pelo INCRA",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva as pendencias ou exigencias tecnicas do INCRA...",
                "ajuda": "Registre as pendencias formalizadas pelo INCRA para aprovacao.",
            },
            {
                "id": "sigef18_data_protocolo",
                "secao": "Prazos",
                "tipo": "text",
                "label": "Data do Protocolo no SIGEF",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 15/03/2024",
                "ajuda": "Data em que o processo foi protocolado no sistema SIGEF.",
            },
            {
                "id": "sigef18_numero_certificacao",
                "secao": "Prazos",
                "tipo": "text",
                "label": "Numero da Certificacao INCRA",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: INCRA/SR-09/2024/00123",
                "ajuda": "Numero do certificado emitido pelo INCRA (quando aprovado).",
            },
        ],
        "secoes_obrigatorias": [
            "Identificacao SIGEF",
            "Pendencias",
            "Prazos",
        ],
    },
]
