# @module seed_tvi — Modelos TVI: RURAL/AGRIMENSURA (6) + REGULARIZAÇÃO/INCRA (6)
"""Definições dos modelos TVI das categorias RURAL e REGULARIZAÇÃO."""
from seed_tvi_base import CAMPOS_BASE

MODELOS_RURAL = [
    {
        "nome": "Vistoria Rural (Caracterização)",
        "tipo": "rural_caracterizacao",
        "categoria": "RURAL/AGRIMENSURA",
        "descricao": "Caracterização técnica de imóvel rural",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "area_ha",             "label": "Área Total (ha)",           "type": "number"},
            {"key": "ccir",                "label": "CCIR",                      "type": "text"},
            {"key": "nirf_cib",            "label": "NIRF/CIB",                  "type": "text"},
            {"key": "car",                 "label": "CAR",                       "type": "text"},
            {"key": "uso_solo",            "label": "Uso do Solo",               "type": "textarea"},
            {"key": "benfeitorias_rurais", "label": "Benfeitorias Rurais",       "type": "textarea"},
            {"key": "topografia",          "label": "Topografia",                "type": "text"},
            {"key": "recursos_hidricos",   "label": "Recursos Hídricos",         "type": "textarea"},
        ],
    },
    {
        "nome": "Vistoria de Georreferenciamento",
        "tipo": "rural_georreferenciamento",
        "categoria": "RURAL/AGRIMENSURA",
        "descricao": "Vistoria para fins de georreferenciamento de imóvel rural",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "area_ha",             "label": "Área Total (ha)",           "type": "number"},
            {"key": "sigef_codigo",        "label": "Código SIGEF",              "type": "text"},
            {"key": "datum",               "label": "Sistema Geodésico (Datum)", "type": "text"},
            {"key": "num_vertices",        "label": "Número de Vértices",        "type": "number"},
            {"key": "memorial_descritivo", "label": "Memorial Descritivo",       "type": "textarea"},
            {"key": "precisao_m",          "label": "Precisão (metros)",         "type": "number"},
        ],
    },
    {
        "nome": "Vistoria de Confrontação",
        "tipo": "rural_confrontacao",
        "categoria": "RURAL/AGRIMENSURA",
        "descricao": "Identificação e registro dos confrontantes do imóvel rural",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "confrontante_norte",  "label": "Confrontante Norte",        "type": "text"},
            {"key": "confrontante_sul",    "label": "Confrontante Sul",          "type": "text"},
            {"key": "confrontante_leste",  "label": "Confrontante Leste",        "type": "text"},
            {"key": "confrontante_oeste",  "label": "Confrontante Oeste",        "type": "text"},
            {"key": "divergencias_limites","label": "Divergências de Limites",   "type": "textarea"},
        ],
    },
    {
        "nome": "Vistoria de Uso e Ocupação do Solo",
        "tipo": "rural_uso_ocupacao_solo",
        "categoria": "RURAL/AGRIMENSURA",
        "descricao": "Levantamento do uso e ocupação do solo rural",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "uso_predominante",    "label": "Uso Predominante",          "type": "text"},
            {"key": "area_preservacao",    "label": "Área de Preservação (ha)",  "type": "number"},
            {"key": "area_producao",       "label": "Área Produtiva (ha)",       "type": "number"},
            {"key": "cobertura_vegetal",   "label": "Cobertura Vegetal",         "type": "textarea"},
            {"key": "conformidade_car",    "label": "Conformidade CAR",          "type": "textarea"},
        ],
    },
    {
        "nome": "Vistoria de Retificação de Área",
        "tipo": "rural_retificacao_area",
        "categoria": "RURAL/AGRIMENSURA",
        "descricao": "Vistoria para fins de retificação de área em cartório",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "area_registrada_ha",  "label": "Área Registrada (ha)",      "type": "number"},
            {"key": "area_apurada_ha",     "label": "Área Apurada (ha)",         "type": "number"},
            {"key": "diferenca_ha",        "label": "Diferença (ha)",            "type": "number"},
            {"key": "justificativa",       "label": "Justificativa da Retificação","type": "textarea"},
            {"key": "documentos_base",     "label": "Documentos Base",           "type": "textarea"},
        ],
    },
    {
        "nome": "Certificação SIGEF",
        "tipo": "rural_certificacao_sigef",
        "categoria": "RURAL/AGRIMENSURA",
        "descricao": "Vistoria e certificação junto ao SIGEF/INCRA",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "sigef_codigo",        "label": "Código SIGEF",              "type": "text"},
            {"key": "status_certificacao", "label": "Status da Certificação",    "type": "text"},
            {"key": "data_protocolo",      "label": "Data do Protocolo",         "type": "date"},
            {"key": "tecnico_credenciado", "label": "Técnico Credenciado INCRA", "type": "text"},
            {"key": "observacoes_sigef",   "label": "Observações SIGEF",         "type": "textarea"},
        ],
    },
]

MODELOS_REGULARIZACAO = [
    {
        "nome": "Regularização INCRA",
        "tipo": "regularizacao_incra",
        "categoria": "REGULARIZAÇÃO/INCRA",
        "descricao": "Vistoria para processos de regularização fundiária junto ao INCRA",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "processo_incra",      "label": "Número do Processo INCRA",  "type": "text"},
            {"key": "modalidade",          "label": "Modalidade de Regularização","type": "text"},
            {"key": "area_ha",             "label": "Área (ha)",                  "type": "number"},
            {"key": "ccir",                "label": "CCIR",                       "type": "text"},
            {"key": "ocupante_nome",       "label": "Nome do Ocupante",           "type": "text"},
            {"key": "tempo_posse_anos",    "label": "Tempo de Posse (anos)",      "type": "number"},
        ],
    },
    {
        "nome": "Vistoria CAR (Cadastro Ambiental Rural)",
        "tipo": "regularizacao_car",
        "categoria": "REGULARIZAÇÃO/INCRA",
        "descricao": "Vistoria para fins de Cadastro Ambiental Rural",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "car_codigo",          "label": "Código CAR",                 "type": "text"},
            {"key": "status_car",          "label": "Status no SICAR",            "type": "text"},
            {"key": "area_imovel_ha",      "label": "Área do Imóvel (ha)",        "type": "number"},
            {"key": "area_app_ha",         "label": "Área APP (ha)",              "type": "number"},
            {"key": "area_rl_ha",          "label": "Área Reserva Legal (ha)",    "type": "number"},
            {"key": "passivo_ambiental",   "label": "Passivo Ambiental",          "type": "textarea"},
        ],
    },
    {
        "nome": "Vistoria para Usucapião",
        "tipo": "regularizacao_usucapiao",
        "categoria": "REGULARIZAÇÃO/INCRA",
        "descricao": "Vistoria técnica para fins de ação de usucapião",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "modalidade_usucapiao","label": "Modalidade de Usucapião",   "type": "text"},
            {"key": "tempo_posse_anos",    "label": "Tempo de Posse (anos)",     "type": "number"},
            {"key": "uso_posse",           "label": "Uso da Posse",              "type": "textarea"},
            {"key": "testemunhos",         "label": "Testemunhos",               "type": "textarea"},
            {"key": "processo_judicial",   "label": "Número do Processo",        "type": "text"},
        ],
    },
    {
        "nome": "Vistoria de Desmembramento",
        "tipo": "regularizacao_desmembramento",
        "categoria": "REGULARIZAÇÃO/INCRA",
        "descricao": "Vistoria técnica para aprovação de desmembramento de imóvel",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "matricula_original",  "label": "Matrícula Original",        "type": "text"},
            {"key": "num_lotes",           "label": "Número de Lotes",           "type": "number"},
            {"key": "area_lote_minimo_m2", "label": "Área Mínima do Lote (m²)",  "type": "number"},
            {"key": "processo_municipio",  "label": "Processo na Prefeitura",    "type": "text"},
            {"key": "parecer_tecnico",     "label": "Parecer Técnico",           "type": "textarea"},
        ],
    },
    {
        "nome": "Vistoria de Remembramento",
        "tipo": "regularizacao_remembramento",
        "categoria": "REGULARIZAÇÃO/INCRA",
        "descricao": "Vistoria técnica para aprovação de remembramento (fusão) de imóveis",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "matriculas_envolvidas","label": "Matrículas Envolvidas",    "type": "textarea"},
            {"key": "area_total_resultante","label": "Área Total Resultante (m²)","type": "number"},
            {"key": "processo_municipio",  "label": "Processo na Prefeitura",    "type": "text"},
            {"key": "justificativa",       "label": "Justificativa",             "type": "textarea"},
        ],
    },
    {
        "nome": "Vistoria para Registro em Cartório",
        "tipo": "regularizacao_registro_cartorio",
        "categoria": "REGULARIZAÇÃO/INCRA",
        "descricao": "Vistoria para suporte ao processo de registro de imóvel em cartório",
        "campos": CAMPOS_BASE,
        "campos_especificos": [
            {"key": "cartorio_nome",       "label": "Cartório",                  "type": "text"},
            {"key": "livro_folha",         "label": "Livro/Folha",               "type": "text"},
            {"key": "tipo_registro",       "label": "Tipo de Registro",          "type": "text"},
            {"key": "documentos_exigidos", "label": "Documentos Exigidos",       "type": "textarea"},
            {"key": "pendencias",          "label": "Pendências para Registro",  "type": "textarea"},
        ],
    },
]
