# @module seed_tvi — Modelos TVI Ramos 4-5: REGULARIZACAO (TVI-19 a TVI-24) + OBRAS (TVI-25 a TVI-29)
"""
Modelos profissionais dos Ramos REGULARIZACAO e OBRAS com novo schema unificado.
Cada campo possui id EXCLUSIVO — nenhum campo e compartilhado entre modelos.
Schema: {id, nome, ramo, aplicacao, normas, requer_art, campos_especificos, secoes_obrigatorias}
"""

MODELOS_REGULARIZACAO = [
    # TVI-19 — Regularizacao INCRA
    {
        "id": "TVI-19",
        "nome": "Vistoria de Regularizacao Fundiaria — INCRA",
        "ramo": "REGULARIZACAO",
        "aplicacao": "Vistoria para instrucao de processo de regularizacao fundiaria junto ao INCRA, "
                     "verificando condicoes de ocupacao, destinacao social e documentacao do ocupante.",
        "normas": [
            "Lei 11.952/2009 — Regularizacao fundiaria Amazonia Legal",
            "Lei 13.465/2017 — Regularizacao fundiaria urbana e rural",
            "IN INCRA 85/2015 — Titulacao de assentamentos",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "incra19_modalidade",
                "secao": "Dados do Processo",
                "tipo": "select",
                "label": "Modalidade de Regularizacao",
                "opcoes": [
                    "Titulacao de assentamento",
                    "Regularizacao de posseiros",
                    "Demarcacao de territorio",
                    "Legitimacao fundiaria",
                    "Concessao de uso",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Modalidade do processo de regularizacao junto ao INCRA.",
            },
            {
                "id": "incra19_norma_aplicavel",
                "secao": "Dados do Processo",
                "tipo": "text",
                "label": "Norma/Instrucao Normativa Aplicavel",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: IN INCRA 85/2015",
                "ajuda": "Instrucao normativa especifica que rege o processo.",
            },
            {
                "id": "incra19_situacao_ocupacional",
                "secao": "Situacao do Ocupante",
                "tipo": "select",
                "label": "Situacao Ocupacional",
                "opcoes": [
                    "Ocupante com titulo precario",
                    "Ocupante sem titulo — posse mansa e pacifica",
                    "Beneficiario de assentamento",
                    "Posseiro com conflito",
                    "Sem ocupacao atual",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao ocupacional atual do requerente.",
            },
            {
                "id": "incra19_tempo_ocupacao_anos",
                "secao": "Situacao do Ocupante",
                "tipo": "number",
                "label": "Tempo de Ocupacao (anos)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 15",
                "ajuda": "Tempo de ocupacao contado desde o inicio da posse.",
            },
            {
                "id": "incra19_destinacao_social",
                "secao": "Situacao do Ocupante",
                "tipo": "caixa_texto",
                "label": "Destinacao Social do Imovel",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: moradia familiar com extrativismo vegetal...",
                "ajuda": "Descreva a funcao social da propriedade conforme Art. 186 CF.",
            },
            {
                "id": "incra19_documentos_ocupante",
                "secao": "Documentacao",
                "tipo": "multiselect",
                "label": "Documentos do Ocupante Verificados",
                "opcoes": [
                    "RG / CPF",
                    "Comprovante de residencia",
                    "Certidao de casamento",
                    "Declaracao de posse",
                    "Recibos de pagamento de ITR",
                    "Documentos de melhoria (notas fiscais)",
                    "Testemunhos de posse",
                    "DAP/CAF (agricultor familiar)",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque os documentos do ocupante verificados na vistoria.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados do Processo",
            "Situacao do Ocupante",
            "Documentacao",
        ],
    },

    # TVI-20 — CAR
    {
        "id": "TVI-20",
        "nome": "Vistoria CAR — Cadastro Ambiental Rural",
        "ramo": "REGULARIZACAO",
        "aplicacao": "Vistoria para inscricao, regularizacao ou verificacao do Cadastro Ambiental Rural, "
                     "mapeando reserva legal, APPs e verificando sobreposicoes.",
        "normas": [
            "Lei 12.651/2012 Art. 29 — CAR obrigatorio",
            "Decreto 7.830/2012 — SICAR",
            "IN MMA 02/2014 — Registro no CAR",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "car20_numero_car",
                "secao": "Identificacao CAR",
                "tipo": "text",
                "label": "Numero do CAR (codigo no SICAR)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: PR-4106902-1234567890ABCDEF",
                "ajuda": "Codigo completo do CAR conforme protocolo no SICAR estadual.",
            },
            {
                "id": "car20_status_sicar",
                "secao": "Identificacao CAR",
                "tipo": "select",
                "label": "Status no SICAR",
                "opcoes": [
                    "Ativo — analisado e aprovado",
                    "Ativo — em analise",
                    "Pendente de complementacao",
                    "Aguardando analise",
                    "Cancelado",
                    "Nao inscrito",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao atual do CAR no sistema SICAR.",
            },
            {
                "id": "car20_reserva_legal_ha",
                "secao": "Reserva Legal",
                "tipo": "number",
                "label": "Reserva Legal Declarada (ha)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 9.16",
                "ajuda": "Area de reserva legal declarada no CAR em hectares.",
            },
            {
                "id": "car20_apps_mapeadas",
                "secao": "APPs",
                "tipo": "tabela",
                "label": "APPs Mapeadas no CAR",
                "opcoes": ["Tipo de APP", "Area (ha)", "Situacao (preservada/degradada)", "Observacoes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Liste cada APP com tipo, area e estado de conservacao.",
            },
            {
                "id": "car20_sobreposicao_terras_publicas",
                "secao": "Inconsistencias",
                "tipo": "caixa_texto",
                "label": "Sobreposicao com Terras Publicas",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva eventual sobreposicao com UCs, terras indigenas ou outros...",
                "ajuda": "Informe se ha sobreposicao com terras publicas identificada pelo SICAR.",
            },
            {
                "id": "car20_pendencias_car",
                "secao": "Inconsistencias",
                "tipo": "caixa_texto",
                "label": "Pendencias do CAR",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: complementacao de geometria, documentos pendentes...",
                "ajuda": "Registre as pendencias formalizadas pelo orgao ambiental estadual.",
            },
        ],
        "secoes_obrigatorias": [
            "Identificacao CAR",
            "Reserva Legal",
            "APPs",
            "Inconsistencias",
        ],
    },

    # TVI-21 — Usucapiao
    {
        "id": "TVI-21",
        "nome": "Vistoria para Usucapiao",
        "ramo": "REGULARIZACAO",
        "aplicacao": "Vistoria tecnica para instrucao de acao de usucapiao, comprovando tempo de posse, "
                     "modalidade, area reivindicada e ausencia de oposicao.",
        "normas": [
            "CC/2002 Art. 1.238 a 1.244 — Usucapiao",
            "CPC/2015 Art. 1.071 — Usucapiao extrajudicial",
            "Lei 13.465/2017 — Usucapiao extrajudicial",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "usu21_modalidade",
                "secao": "Dados da Posse",
                "tipo": "select",
                "label": "Modalidade de Usucapiao",
                "opcoes": [
                    "Ordinaria (CC Art. 1.242 — 10 anos)",
                    "Extraordinaria (CC Art. 1.238 — 15 anos ou 10 anos)",
                    "Especial urbana (CC Art. 1.240 — 5 anos)",
                    "Especial rural (CC Art. 1.239 — 5 anos)",
                    "Familiar (CC Art. 1.240-A — 2 anos)",
                    "Coletiva urbana (Est. Cidade Art. 10)",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Modalidade de usucapiao com base no tempo de posse e finalidade.",
            },
            {
                "id": "usu21_tempo_posse_anos",
                "secao": "Dados da Posse",
                "tipo": "number",
                "label": "Tempo Comprovado de Posse (anos)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 12",
                "ajuda": "Tempo de posse mansa e continua verificado e documentado.",
            },
            {
                "id": "usu21_posse_mansa",
                "secao": "Dados da Posse",
                "tipo": "select",
                "label": "Posse Mansa e Pacifica",
                "opcoes": [
                    "Sim — sem contestacao",
                    "Nao — ha contestacao de terceiro",
                    "Contestada — em apuracao judicial",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Informe se a posse e mansa, pacifica e sem interrupcao.",
            },
            {
                "id": "usu21_finalidade",
                "secao": "Dados da Posse",
                "tipo": "select",
                "label": "Finalidade da Posse",
                "opcoes": [
                    "Moradia propria",
                    "Moradia familiar",
                    "Atividade produtiva rural",
                    "Uso comercial",
                    "Uso misto",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Finalidade do uso do imovel durante o periodo de posse.",
            },
            {
                "id": "usu21_area_reivindicada_m2",
                "secao": "Area",
                "tipo": "number",
                "label": "Area Reivindicada (m²)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 250.00",
                "ajuda": "Area total objeto do pedido de usucapiao em metros quadrados.",
            },
            {
                "id": "usu21_oposicao_terceiros",
                "secao": "Dados da Posse",
                "tipo": "caixa_texto",
                "label": "Oposicao de Terceiros",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva eventuais oposicoes identificadas...",
                "ajuda": "Registre qualquer oposicao, contestacao ou disputa sobre a posse.",
            },
            {
                "id": "usu21_numero_processo_jud",
                "secao": "Dados Processuais",
                "tipo": "text",
                "label": "Numero do Processo Judicial / Extrajudicial",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 0001234-56.2024.8.26.0001",
                "ajuda": "Numero do processo judicial ou procedimento extrajudicial no CRI.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados da Posse",
            "Area",
            "Dados Processuais",
        ],
    },

    # TVI-22 — Desmembramento
    {
        "id": "TVI-22",
        "nome": "Vistoria de Desmembramento de Imovel",
        "ramo": "REGULARIZACAO",
        "aplicacao": "Vistoria tecnica para aprovacao de desmembramento de imovel urbano, verificando "
                     "conformidade com Lei 6.766/79 e exigencias municipais de infraestrutura.",
        "normas": [
            "Lei 6.766/1979 — Parcelamento do solo urbano",
            "NBR 12267:1992 — Normas para elaboracao de planta de situacao para licenciamento",
            "Lei Municipal de Parcelamento do Solo",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "desm22_area_total_m2",
                "secao": "Dados do Imovel",
                "tipo": "number",
                "label": "Area Total do Imovel Original (m²)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 1200.00",
                "ajuda": "Area total do imovel antes do desmembramento.",
            },
            {
                "id": "desm22_numero_lotes",
                "secao": "Dados do Imovel",
                "tipo": "number",
                "label": "Numero de Lotes Resultantes",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 3",
                "ajuda": "Quantidade de lotes criados pelo desmembramento.",
            },
            {
                "id": "desm22_frente_minima_m",
                "secao": "Conformidade Urbanistica",
                "tipo": "number",
                "label": "Frente Minima de Cada Lote (m)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 8.0",
                "ajuda": "Medida de frente do menor lote. Lei 6.766/79 exige minimo de 5m para certos casos.",
            },
            {
                "id": "desm22_conformidade_lei6766",
                "secao": "Conformidade Urbanistica",
                "tipo": "select",
                "label": "Conformidade com Lei 6.766/79",
                "opcoes": [
                    "Conforme — todos os lotes atendem os minimos",
                    "Conforme com excecao municipal aprovada",
                    "Nao conforme — exige adaptacao",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Verifique se os lotes atendem area e frente minimos da lei.",
            },
            {
                "id": "desm22_aprovacao_prefeitura",
                "secao": "Situacao Legal",
                "tipo": "select",
                "label": "Aprovacao pela Prefeitura",
                "opcoes": [
                    "Aprovado — alvara emitido",
                    "Em analise",
                    "Pendente de documentacao",
                    "Indeferido",
                    "Nao protocolado",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao do processo de aprovacao municipal.",
            },
            {
                "id": "desm22_infraestrutura",
                "secao": "Infraestrutura",
                "tipo": "multiselect",
                "label": "Infraestrutura Disponivel",
                "opcoes": [
                    "Agua — rede publica",
                    "Esgoto — rede publica",
                    "Energia eletrica",
                    "Pavimentacao",
                    "Iluminacao publica",
                    "Coleta de lixo",
                    "Drenagem de aguas pluviais",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque toda a infraestrutura disponivel nos lotes.",
            },
            {
                "id": "desm22_servidoes",
                "secao": "Situacao Legal",
                "tipo": "caixa_texto",
                "label": "Servidoes Existentes ou Criadas",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: servidao de passagem — lote 2 para lote 1...",
                "ajuda": "Descreva servidoes que existem ou serao criadas pelo desmembramento.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados do Imovel",
            "Conformidade Urbanistica",
            "Situacao Legal",
            "Infraestrutura",
        ],
    },

    # TVI-23 — Remembramento
    {
        "id": "TVI-23",
        "nome": "Vistoria de Remembramento de Imovel",
        "ramo": "REGULARIZACAO",
        "aplicacao": "Vistoria tecnica para aprovacao de remembramento (fusao) de dois ou mais imoveis, "
                     "verificando conformidade com zoneamento e exigencias municipais.",
        "normas": [
            "Lei 6.766/1979 — Parcelamento do solo",
            "Lei Municipal de Uso e Ocupacao do Solo",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "rem23_matriculas_tabela",
                "secao": "Imoveis Envolvidos",
                "tipo": "tabela",
                "label": "Matriculas dos Imoveis a Remembrar",
                "opcoes": ["Matricula", "Area (m²)", "Proprietario", "Cartorio", "Observacoes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Liste todas as matriculas dos imoveis que serao fundidos.",
            },
            {
                "id": "rem23_areas_individuais_soma",
                "secao": "Imoveis Envolvidos",
                "tipo": "number",
                "label": "Soma das Areas Individuais (m²)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 800.00",
                "ajuda": "Soma das areas de todos os imoveis antes do remembramento.",
            },
            {
                "id": "rem23_area_resultante_m2",
                "secao": "Imovel Resultante",
                "tipo": "number",
                "label": "Area do Imovel Resultante (m²)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 800.00",
                "ajuda": "Area total do novo imovel resultante do remembramento.",
            },
            {
                "id": "rem23_aprovacao_municipal",
                "secao": "Situacao Legal",
                "tipo": "select",
                "label": "Aprovacao Municipal",
                "opcoes": [
                    "Aprovado pela prefeitura",
                    "Em analise",
                    "Pendente de documentacao",
                    "Dispensado de aprovacao",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao da aprovacao do remembramento na prefeitura.",
            },
            {
                "id": "rem23_zoneamento_permite",
                "secao": "Imovel Resultante",
                "tipo": "select",
                "label": "Zoneamento Permite o Remembramento",
                "opcoes": [
                    "Sim — sem restricao de area maxima",
                    "Sim — dentro do limite de area maxima",
                    "Nao — area resultante excede limite zonal",
                    "Verificacao pendente",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Confirme se o zoneamento municipal permite o imovel com a area resultante.",
            },
            {
                "id": "rem23_recuo_testada_resultante",
                "secao": "Imovel Resultante",
                "tipo": "caixa_texto",
                "label": "Recuos e Testada do Imovel Resultante",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: testada resultante — 20m; recuo frontal — 5m...",
                "ajuda": "Descreva a testada e recuos do imovel resultante.",
            },
        ],
        "secoes_obrigatorias": [
            "Imoveis Envolvidos",
            "Imovel Resultante",
            "Situacao Legal",
        ],
    },

    # TVI-24 — Registro em Cartorio
    {
        "id": "TVI-24",
        "nome": "Vistoria para Registro em Cartorio",
        "ramo": "REGULARIZACAO",
        "aplicacao": "Vistoria tecnica para subsidiar o processo de registro ou averbacao de imovel em "
                     "cartorio de registro de imoveis, identificando pendencias documentais.",
        "normas": [
            "Lei 6.015/1973 — Registros Publicos",
            "Provimento CNJ 150/2023",
            "Lei Estadual de Custas Cartorariais",
        ],
        "requer_art": False,
        "campos_especificos": [
            {
                "id": "cart24_cartorio_competente",
                "secao": "Dados do Cartorio",
                "tipo": "text",
                "label": "Cartorio Competente",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 1o Oficio de Registro de Imoveis de Curitiba-PR",
                "ajuda": "Cartorio de Registro de Imoveis competente para o imovel.",
            },
            {
                "id": "cart24_matricula_numero",
                "secao": "Dados do Cartorio",
                "tipo": "text",
                "label": "Numero da Matricula",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 12.345",
                "ajuda": "Numero da matricula do imovel no CRI.",
            },
            {
                "id": "cart24_documentos_pendentes",
                "secao": "Pendencias",
                "tipo": "multiselect",
                "label": "Documentos Pendentes para Registro",
                "opcoes": [
                    "Escritura publica",
                    "Formal de partilha / Alvara judicial",
                    "Habite-se / Auto de conclusao",
                    "ART/TRT da construcao",
                    "Memorial descritivo e planta",
                    "IPTU quitado",
                    "ITBI pago",
                    "Certidao negativa INCRA (rural)",
                    "Certidao de anuencia do municipio",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque os documentos ainda pendentes para o registro.",
            },
            {
                "id": "cart24_itbi_situacao",
                "secao": "Situacao Fiscal",
                "tipo": "select",
                "label": "ITBI — Situacao",
                "opcoes": ["Pago — guia quitada", "Pendente — guia emitida", "Isento — justificativa", "Nao aplicavel"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao do Imposto de Transmissao de Bens Imoveis.",
            },
            {
                "id": "cart24_prazo_estimado",
                "secao": "Previsao",
                "tipo": "text",
                "label": "Prazo Estimado para Conclusao do Registro",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 30 dias apos apresentacao completa dos documentos",
                "ajuda": "Estimativa de prazo para concluir o registro considerando as pendencias.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados do Cartorio",
            "Pendencias",
            "Situacao Fiscal",
            "Previsao",
        ],
    },
]

MODELOS_OBRAS = [
    # TVI-25 — Acompanhamento de Obra
    {
        "id": "TVI-25",
        "nome": "Vistoria de Acompanhamento de Obra",
        "ramo": "OBRAS",
        "aplicacao": "Registro periodico do andamento fisico da obra com medicao de avanco, controle "
                     "de cronograma, mao de obra, materiais e identificacao de nao conformidades.",
        "normas": [
            "NBR 12006:1990 — Execucao de estruturas de concreto",
            "NR-18 — Seguranca na construcao",
            "Resolucao CONFEA 1.094/2017 — ART",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "obra25_numero_vistoria_seq",
                "secao": "Identificacao da Vistoria",
                "tipo": "number",
                "label": "Numero da Vistoria de Acompanhamento",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 5",
                "ajuda": "Numero de ordem desta visita de acompanhamento.",
            },
            {
                "id": "obra25_avanco_fisico_pct",
                "secao": "Medicao de Avanco",
                "tipo": "number",
                "label": "Avanco Fisico Global da Obra (%)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 65.0",
                "ajuda": "Percentual de avanco fisico global calculado na data da vistoria.",
            },
            {
                "id": "obra25_cronograma_previsto_vs_executado",
                "secao": "Medicao de Avanco",
                "tipo": "select",
                "label": "Situacao do Cronograma (Previsto vs. Executado)",
                "opcoes": [
                    "Conforme — dentro do prazo",
                    "Adiantado em relacao ao cronograma",
                    "Atraso de ate 15 dias",
                    "Atraso de 15 a 30 dias",
                    "Atraso superior a 30 dias",
                    "Cronograma nao disponivel",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Compare o avanco previsto com o realizado na data da vistoria.",
            },
            {
                "id": "obra25_servicos_executados",
                "secao": "Servicos",
                "tipo": "tabela",
                "label": "Servicos Executados desde a Ultima Vistoria",
                "opcoes": ["Servico", "Unidade", "Quantidade", "% Concluido", "Observacoes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Liste os servicos executados no periodo com quantidade e percentual.",
            },
            {
                "id": "obra25_servicos_pendentes",
                "secao": "Servicos",
                "tipo": "tabela",
                "label": "Servicos Pendentes",
                "opcoes": ["Servico", "% Pendente", "Prazo previsto", "Responsavel", "Observacoes"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste os servicos ainda nao iniciados ou incompletos.",
            },
            {
                "id": "obra25_mao_obra_presente",
                "secao": "Recursos",
                "tipo": "number",
                "label": "Mao de Obra Presente (numero de trabalhadores)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 18",
                "ajuda": "Numero de trabalhadores presentes no canteiro na data da vistoria.",
            },
            {
                "id": "obra25_materiais_estoque",
                "secao": "Recursos",
                "tipo": "caixa_texto",
                "label": "Materiais em Estoque",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: concreto — 20m3; aco CA-50 — 500kg; tijolos — 10 paletes...",
                "ajuda": "Descreva os principais materiais em estoque no canteiro.",
            },
            {
                "id": "obra25_medicao_valor_rs",
                "secao": "Medicao de Avanco",
                "tipo": "number",
                "label": "Valor Medicao do Periodo (R$)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 85000.00",
                "ajuda": "Valor financeiro da medicao aprovada para o periodo.",
            },
            {
                "id": "obra25_nao_conformidades",
                "secao": "Nao Conformidades",
                "tipo": "tabela",
                "label": "Nao Conformidades Identificadas",
                "opcoes": ["Codigo", "Descricao", "Local na obra", "Gravidade", "Acao corretiva", "Prazo"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Registre cada nao conformidade com local, gravidade e acao corretiva.",
            },
        ],
        "secoes_obrigatorias": [
            "Identificacao da Vistoria",
            "Medicao de Avanco",
            "Servicos",
            "Recursos",
            "Nao Conformidades",
        ],
    },

    # TVI-26 — Entrega de Obra
    {
        "id": "TVI-26",
        "nome": "Vistoria de Entrega de Obra",
        "ramo": "OBRAS",
        "aplicacao": "Registro tecnico na entrega final da obra ao contratante, verificando conformidade "
                     "de projeto, punch list, testes de sistemas e habite-se.",
        "normas": [
            "NBR 15575:2013 — Desempenho",
            "NBR 16280:2015 — Manutencao",
            "Resolucao CONFEA 1.094/2017 — ART de conclusao",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "entob26_conformidade_projeto_pct",
                "secao": "Conformidade",
                "tipo": "number",
                "label": "Conformidade com Projeto (%)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 98.5",
                "ajuda": "Percentual de conformidade entre o projeto aprovado e a obra entregue.",
            },
            {
                "id": "entob26_memorial_item_a_item",
                "secao": "Conformidade",
                "tipo": "tabela",
                "label": "Verificacao do Memorial Descritivo — Item a Item",
                "opcoes": ["Item do memorial", "Especificacao prevista", "Entregue", "Conforme (S/N)", "Observacao"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Verifique cada item do memorial descritivo com o que foi efetivamente entregue.",
            },
            {
                "id": "entob26_testes_realizados",
                "secao": "Testes",
                "tipo": "multiselect",
                "label": "Testes Realizados",
                "opcoes": [
                    "Teste hidraulico — pressao",
                    "Teste de estanqueidade (gas e agua)",
                    "Teste eletrico — continuidade e isolamento",
                    "Ensaio estrutural",
                    "Teste de sistema de combate a incendio",
                    "Teste de impermeabilizacao (inundacao)",
                    "Teste de ventilacao e exaustao",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque todos os testes realizados e aprovados na obra.",
            },
            {
                "id": "entob26_punch_list",
                "secao": "Punch List",
                "tipo": "tabela",
                "label": "Punch List — Pendencias na Entrega",
                "opcoes": ["Item", "Local", "Descricao da pendencia", "Responsavel", "Prazo", "Status"],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Liste todas as pendencias que devem ser resolvidas apos a entrega formal.",
            },
            {
                "id": "entob26_prazo_resolucao_punch",
                "secao": "Punch List",
                "tipo": "text",
                "label": "Prazo Global para Resolucao do Punch List",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 30 dias corridos apos emissao do termo de entrega",
                "ajuda": "Prazo acordado para resolucao de todos os itens do punch list.",
            },
            {
                "id": "entob26_habite_se_situacao",
                "secao": "Documentacao Legal",
                "tipo": "select",
                "label": "Habite-se / Auto de Conclusao",
                "opcoes": [
                    "Emitido — em maos do contratante",
                    "Emitido — em tramite cartorial",
                    "Protocolado — aguardando emissao",
                    "Nao protocolado",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Situacao do habite-se na data de entrega da obra.",
            },
            {
                "id": "entob26_art_conclusao",
                "secao": "Documentacao Legal",
                "tipo": "text",
                "label": "ART de Conclusao de Obra",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: ART CREA 2024-987654-3",
                "ajuda": "Numero da ART de conclusao de obra emitida pelo responsavel tecnico.",
            },
        ],
        "secoes_obrigatorias": [
            "Conformidade",
            "Testes",
            "Punch List",
            "Documentacao Legal",
        ],
    },

    # TVI-27 — Patologias
    {
        "id": "TVI-27",
        "nome": "Vistoria de Patologias Construtivas",
        "ramo": "OBRAS",
        "aplicacao": "Identificacao, diagnostico e plano de intervencao de patologias construtivas em "
                     "edificacoes, abrangendo estrutura, fachadas, cobertura e revestimentos.",
        "normas": [
            "NBR 9575:2010 — Impermeabilizacao",
            "NBR 15575:2013 — Desempenho",
            "NBR 6118:2014 — Estruturas de concreto",
            "NBR 13755:2017 — Revestimentos ceramicos de fachadas",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "pat27_tipo_estrutura",
                "secao": "Caracterizacao da Edificacao",
                "tipo": "multiselect",
                "label": "Tipo de Estrutura da Edificacao",
                "opcoes": [
                    "Alvenaria estrutural",
                    "Concreto armado",
                    "Estrutura metalica",
                    "Estrutura mista (concreto + metal)",
                    "Madeira",
                    "Pre-moldado / Pre-fabricado",
                    "Drywall (nao estrutural)",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque o(s) sistema(s) estrutural(is) da edificacao.",
            },
            {
                "id": "pat27_revestimentos_por_fachada",
                "secao": "Caracterizacao da Edificacao",
                "tipo": "tabela",
                "label": "Revestimentos por Fachada",
                "opcoes": ["Fachada (N/S/L/O)", "Tipo de revestimento", "Ano de aplicacao aprox.", "Estado geral", "Observacoes"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Identifique o revestimento e estado de cada fachada da edificacao.",
            },
            {
                "id": "pat27_cobertura_sistema",
                "secao": "Caracterizacao da Edificacao",
                "tipo": "multiselect",
                "label": "Sistema de Cobertura",
                "opcoes": [
                    "Telha ceramica",
                    "Telha de concreto",
                    "Telha metalica (aco/aluminio/zinco)",
                    "Telha fibrocimento (sem amianto)",
                    "Laje impermeabilizada",
                    "Telhado verde",
                    "Membrana PVC",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque o(s) sistema(s) de cobertura existentes.",
            },
            {
                "id": "pat27_patologias_tabela",
                "secao": "Patologias Identificadas",
                "tipo": "tabela",
                "label": "Catalogo de Patologias",
                "opcoes": ["Tipo", "Local", "Gravidade (leve/moderada/grave/critica)", "Causa provavel", "Intervencao indicada", "Foto ref."],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Registre cada patologia com tipo, local, gravidade, causa e intervencao.",
            },
            {
                "id": "pat27_classificacao_abertura_fissuras",
                "secao": "Patologias Identificadas",
                "tipo": "select",
                "label": "Classificacao de Abertura de Fissuras (maior observada)",
                "opcoes": [
                    "Fissura — abertura < 0,5 mm",
                    "Trinca — abertura 0,5 a 2,0 mm",
                    "Rachadura — abertura 2,0 a 10,0 mm",
                    "Fenda — abertura > 10,0 mm",
                    "Sem fissuras identificadas",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Classificacao da maior abertura de fissura observada conforme NBR 6118.",
            },
            {
                "id": "pat27_nivel_degradacao",
                "secao": "Diagnostico",
                "tipo": "select",
                "label": "Nivel Global de Degradacao da Edificacao",
                "opcoes": [
                    "Leve — manutencao preventiva",
                    "Moderado — manutencao corretiva simples",
                    "Grave — intervencao de media complexidade",
                    "Critico — intervencao urgente / interdição",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Avaliacao global do nivel de degradacao da edificacao.",
            },
            {
                "id": "pat27_mecanismo_evolucao",
                "secao": "Diagnostico",
                "tipo": "caixa_texto",
                "label": "Mecanismo de Evolucao das Patologias",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Descreva como as patologias evoluem se nao tratadas...",
                "ajuda": "Explique o mecanismo de propagacao e evolucao das patologias identificadas.",
            },
            {
                "id": "pat27_plano_intervencao",
                "secao": "Plano de Intervencao",
                "tipo": "tabela",
                "label": "Plano de Intervencao",
                "opcoes": ["Acao corretiva", "Prazo recomendado", "Prioridade (alta/media/baixa)", "Responsavel", "Estimativa (R$)"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Elabore o plano de intervencao com acoes, prazos e prioridades.",
            },
        ],
        "secoes_obrigatorias": [
            "Caracterizacao da Edificacao",
            "Patologias Identificadas",
            "Diagnostico",
            "Plano de Intervencao",
        ],
    },

    # TVI-28 — Estrutural
    {
        "id": "TVI-28",
        "nome": "Vistoria Estrutural",
        "ramo": "OBRAS",
        "aplicacao": "Avaliacao tecnica da integridade estrutural da edificacao, verificando fundacoes, "
                     "sistemas estruturais, estado das armaduras e necessidade de laudos complementares.",
        "normas": [
            "NBR 6118:2014 — Projeto de estruturas de concreto",
            "NBR 6122:2019 — Projeto e execucao de fundacoes",
            "NBR 15575:2013 — Desempenho",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "est28_tipo_fundacao",
                "secao": "Fundacoes",
                "tipo": "select",
                "label": "Tipo de Fundacao",
                "opcoes": [
                    "Sapata isolada",
                    "Sapata corrida",
                    "Radier",
                    "Estaca helice continua",
                    "Estaca raiz",
                    "Estaca escavada",
                    "Tubulao a ceu aberto",
                    "Tubulao a ar comprimido",
                    "Nao identificado",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Tipo de fundacao da edificacao conforme projeto ou levantamento.",
            },
            {
                "id": "est28_sistema_estrutural",
                "secao": "Sistema Estrutural",
                "tipo": "caixa_texto",
                "label": "Descricao do Sistema Estrutural",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: porticos de concreto armado com lajes cogumelo, fck=25MPa...",
                "ajuda": "Descreva o sistema estrutural da edificacao: material, geometria e caracteristicas.",
            },
            {
                "id": "est28_fck_estimado_mpa",
                "secao": "Sistema Estrutural",
                "tipo": "number",
                "label": "fck Estimado (MPa)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 25.0",
                "ajuda": "Resistencia caracteristica do concreto estimada por ensaio ou projeto.",
            },
            {
                "id": "est28_carbonatacao",
                "secao": "Estado das Armaduras",
                "tipo": "checkbox",
                "label": "Carbonatacao Identificada",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Marque se foi identificada carbonatacao do concreto (frente de carbonatacao).",
            },
            {
                "id": "est28_cobrimento_mm",
                "secao": "Estado das Armaduras",
                "tipo": "number",
                "label": "Cobrimento Medido (mm)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 25.0",
                "ajuda": "Cobrimento medio das armaduras medido com pachometro.",
            },
            {
                "id": "est28_armadura_corrosao",
                "secao": "Estado das Armaduras",
                "tipo": "select",
                "label": "Estado de Corrosao das Armaduras",
                "opcoes": [
                    "Sem corrosao — cobrimento integro",
                    "Inicio de corrosao — manchas superficiais",
                    "Corrosao avancada — fissuras por expansao",
                    "Armadura exposta — sem seccao residual",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Avalie o estado de corrosao das armaduras nos elementos estruturais.",
            },
            {
                "id": "est28_recalque_tipo",
                "secao": "Fundacoes",
                "tipo": "select",
                "label": "Recalque Identificado",
                "opcoes": [
                    "Sem recalque identificado",
                    "Recalque uniforme — sem danos estruturais",
                    "Recalque diferencial — fissuras diagonais",
                    "Recalque grave — risco de colapso",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Tipo de recalque de fundacao identificado na vistoria.",
            },
            {
                "id": "est28_ensaios_realizados",
                "secao": "Ensaios",
                "tipo": "multiselect",
                "label": "Ensaios Realizados",
                "opcoes": [
                    "Esclerometria (dureza superficial)",
                    "Pachometro (localizacao de armaduras)",
                    "GPR — Ground Penetrating Radar",
                    "Carbonatacao (fenolftaleina)",
                    "Extracao de corpo de prova",
                    "Prova de carga estatica",
                    "Nenhum ensaio realizado",
                ],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Marque todos os ensaios realizados durante a vistoria estrutural.",
            },
            {
                "id": "est28_laudo_complementar",
                "secao": "Conclusao",
                "tipo": "checkbox",
                "label": "Laudo Complementar de Especialista Necessario",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "",
                "ajuda": "Marque se e necessario laudo complementar de engenheiro estrutural especialista.",
            },
        ],
        "secoes_obrigatorias": [
            "Fundacoes",
            "Sistema Estrutural",
            "Estado das Armaduras",
            "Ensaios",
            "Conclusao",
        ],
    },

    # TVI-29 — Conformidade Projeto vs. Executado
    {
        "id": "TVI-29",
        "nome": "Vistoria de Conformidade — Projeto vs. Executado",
        "ramo": "OBRAS",
        "aplicacao": "Comparacao tecnica entre o projeto aprovado e a obra efetivamente executada, "
                     "verificando areas, recuos, taxas e uso, identificando acrescimos nao aprovados.",
        "normas": [
            "Lei 6.766/1979",
            "Codigo de Obras Municipal",
            "NBR 13532:1995 — Elaboracao de projetos de edificacoes",
        ],
        "requer_art": True,
        "campos_especificos": [
            {
                "id": "conf29_projeto_numero_orgao_data",
                "secao": "Dados do Projeto",
                "tipo": "text",
                "label": "Projeto Aprovado — Numero, Orgao e Data",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: Proc. 2022/001234 — Secretaria de Obras — aprovado em 10/05/2022",
                "ajuda": "Identificacao do projeto aprovado: numero do processo, orgao aprovador e data.",
            },
            {
                "id": "conf29_area_aprovada_m2",
                "secao": "Comparativo de Areas",
                "tipo": "number",
                "label": "Area Aprovada no Projeto (m²)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 180.00",
                "ajuda": "Area total aprovada no projeto junto ao municipio.",
            },
            {
                "id": "conf29_area_construida_m2",
                "secao": "Comparativo de Areas",
                "tipo": "number",
                "label": "Area Efetivamente Construida (m²)",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: 210.00",
                "ajuda": "Area total construida medida na vistoria.",
            },
            {
                "id": "conf29_uso_aprovado_vs_atual",
                "secao": "Comparativo de Uso",
                "tipo": "caixa_texto",
                "label": "Uso Aprovado vs. Uso Atual",
                "opcoes": [],
                "obrigatorio": True,
                "placeholder": "Ex.: aprovado — residencial unifamiliar; atual — residencial + comercio informal...",
                "ajuda": "Descreva o uso aprovado e o uso atual do imovel.",
            },
            {
                "id": "conf29_recuos_tabela",
                "secao": "Recuos",
                "tipo": "tabela",
                "label": "Recuos — Medido vs. Projeto",
                "opcoes": ["Recuo", "Previsto no projeto (m)", "Medido in loco (m)", "Conforme (S/N)", "Observacao"],
                "obrigatorio": True,
                "placeholder": "",
                "ajuda": "Compare os recuos frontais, laterais e de fundos com o projeto aprovado.",
            },
            {
                "id": "conf29_taxa_ocupacao_aprovada",
                "secao": "Indices Urbanisticos",
                "tipo": "number",
                "label": "Taxa de Ocupacao Aprovada (%)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 60.0",
                "ajuda": "Taxa de ocupacao do terreno aprovada no projeto.",
            },
            {
                "id": "conf29_taxa_ocupacao_real",
                "secao": "Indices Urbanisticos",
                "tipo": "number",
                "label": "Taxa de Ocupacao Real (%)",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 72.5",
                "ajuda": "Taxa de ocupacao real medida na vistoria.",
            },
            {
                "id": "conf29_coeficiente_aproveitamento",
                "secao": "Indices Urbanisticos",
                "tipo": "number",
                "label": "Coeficiente de Aproveitamento Real",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: 1.75",
                "ajuda": "Relacao entre a area construida total e a area do terreno.",
            },
            {
                "id": "conf29_acrescimos_nao_aprovados",
                "secao": "Nao Conformidades",
                "tipo": "caixa_texto",
                "label": "Acrescimos / Construcoes Nao Aprovados",
                "opcoes": [],
                "obrigatorio": False,
                "placeholder": "Ex.: ampliacao de 30m2 nos fundos, cobertura em area de recuo lateral...",
                "ajuda": "Descreva as construcoes executadas sem aprovacao municipal.",
            },
        ],
        "secoes_obrigatorias": [
            "Dados do Projeto",
            "Comparativo de Areas",
            "Comparativo de Uso",
            "Recuos",
            "Indices Urbanisticos",
            "Nao Conformidades",
        ],
    },
]
